/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insumos;

import ConexionBDD.Timer1;
import insumos.ListaInsumos;
import clases.Accion;
import clases.Insumo;
import clases.MainTransaccion;
import clases.Notificacion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import static sistema_inventario.Inicio.usuario_iniciado;
import static insumos.Pantalla_1.InsumoScroll;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.Timer;
import static sistema_inventario.Menu_principal.pantalla1;


/**
 *
 * @author windows
 */
public class Crear extends javax.swing.JPanel {

    /**
     * Creates new form Crear
     */
    private ButtonGroup bg;
    int con = 0;
    int con5 = 0;
    int con3 = 0;
    int con1 = 0;
    
    private Timer1  t = new Timer1();
   
    
    private double condicion = 0;
    
    private double resultado = 0;
    private JLabel guia;
    public Crear() {
        initComponents();

        setBounds(0, 0, 1050, 540);
        setPreferredSize(new Dimension(1039, 475));
        this.jDialog2.getContentPane().setBackground(new Color(252, 249, 249));
        setBackground(new Color(252, 249, 249));
        
       
        
        
       this.combo_tipo.addItem("Unidades (PZA)");
       this.combo_tipo.addItem("Kilogramos (Kg)");
       this.combo_tipo.addItem("Gramos (g)");
       this.combo_tipo.addItem("Miligramos (mg)");
       this.combo_tipo.addItem("Litros (l)");
       this.combo_tipo.addItem("Paquetes (PAQ)");
       this.combo_tipo.addItem("Cajas");
       this.combo_tipo.addItem("Botellas");
       this.combo_tipo.addItem("Otro...");
       
       this.edt_otro.setVisible(false);
       
       iniciarOpciones();
        
       this.edt_otro_cada.setVisible(false);
       this.label_ayuda.setVisible(false);
       this.ruta.setEditable(false);
       
       this.l1_unidades.setVisible(false);
       
       
       
    }
    
    

    private void establecerApariencia(){
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
    }
    private void restablecerApariencia(){
        try {
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        } 
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog(pantalla1, "Calcular Precio Unitario", true);
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_u_cada = new javax.swing.JLabel();
        txt_p_cada = new javax.swing.JLabel();
        combo_opciones = new javax.swing.JComboBox<>();
        edt_cada = new javax.swing.JTextField();
        edt_precio_cada = new javax.swing.JTextField();
        btn_calcular_cada = new javax.swing.JButton();
        label_resultado_cada = new javax.swing.JLabel();
        btn_aceptar_cada = new javax.swing.JButton();
        edt_otro_cada = new javax.swing.JTextField();
        label_unidad = new javax.swing.JLabel();
        l1_unidades = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        iDescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        iNombre = new javax.swing.JTextField();
        iPrecio = new javax.swing.JTextField();
        ruta = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        iCantidad = new javax.swing.JTextField();
        combo_tipo = new javax.swing.JComboBox<>();
        edt_otro = new javax.swing.JTextField();
        btn_ayuda = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        i_minimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        label_ayuda = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jDialog2.setAutoRequestFocus(false);
        jDialog2.setBackground(new java.awt.Color(252, 249, 249));
        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Calcular Precio Unitario");
        jDialog2.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 205, 28));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Forma en que compra:");
        jDialog2.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txt_u_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_u_cada.setText("Unidades por cada:");
        jDialog2.getContentPane().add(txt_u_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txt_p_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_p_cada.setText("Precio por :");
        jDialog2.getContentPane().add(txt_p_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        combo_opciones.setBackground(new java.awt.Color(252, 249, 249));
        combo_opciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combo_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opciones" }));
        combo_opciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_opcionesItemStateChanged(evt);
            }
        });
        jDialog2.getContentPane().add(combo_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, -1));

        edt_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_cada.setText("Ingrese");
        edt_cada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_cadaMouseClicked(evt);
            }
        });
        jDialog2.getContentPane().add(edt_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 79, -1));

        edt_precio_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_precio_cada.setText("Ingrese");
        edt_precio_cada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_precio_cadaMouseClicked(evt);
            }
        });
        jDialog2.getContentPane().add(edt_precio_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 79, -1));

        btn_calcular_cada.setBackground(new java.awt.Color(29, 45, 80));
        btn_calcular_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_calcular_cada.setForeground(new java.awt.Color(255, 255, 255));
        btn_calcular_cada.setText("Calcular");
        btn_calcular_cada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_cadaActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(btn_calcular_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        label_resultado_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_resultado_cada.setText("Resultado");
        jDialog2.getContentPane().add(label_resultado_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 150, -1));

        btn_aceptar_cada.setBackground(new java.awt.Color(29, 45, 80));
        btn_aceptar_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_aceptar_cada.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar_cada.setText("Aceptar");
        btn_aceptar_cada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar_cadaActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(btn_aceptar_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        edt_otro_cada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        edt_otro_cada.setText("Especifique");
        edt_otro_cada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_otro_cadaMouseClicked(evt);
            }
        });
        edt_otro_cada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_otro_cadaActionPerformed(evt);
            }
        });
        edt_otro_cada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edt_otro_cadaKeyReleased(evt);
            }
        });
        jDialog2.getContentPane().add(edt_otro_cada, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 98, -1));

        label_unidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_unidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/question.png"))); // NOI18N
        label_unidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_unidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_unidadMouseExited(evt);
            }
        });
        jDialog2.getContentPane().add(label_unidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 40, -1));

        l1_unidades.setBackground(new java.awt.Color(153, 153, 255));
        l1_unidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1_unidades.setText("Ayuda");
        l1_unidades.setOpaque(true);
        jDialog2.getContentPane().add(l1_unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 140, 60));

        setBackground(new java.awt.Color(252, 249, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 50, 50));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Inventario Mínimo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 190, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 50, 50));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Descripción del Insumo : ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 210, 37));

        iDescripcion.setColumns(20);
        iDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iDescripcion.setLineWrap(true);
        iDescripcion.setTabSize(0);
        iDescripcion.setWrapStyleWord(true);
        iDescripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(iDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 310, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 50, 50));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Precio Unitario:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 220, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 50, 50));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Insertar Imagen");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 190, 140));

        jButton2.setBackground(new java.awt.Color(29, 45, 80));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/upload.png"))); // NOI18N
        jButton2.setText("Subir Imagen");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 270, -1, -1));

        iNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iNombre.setForeground(new java.awt.Color(153, 153, 153));
        iNombre.setText("Nombre del Insumo ");
        iNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iNombreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iNombreMouseEntered(evt);
            }
        });
        iNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iNombreActionPerformed(evt);
            }
        });
        add(iNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 290, 30));

        iPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iPrecio.setForeground(new java.awt.Color(153, 153, 153));
        iPrecio.setText("Ingrese el Precio Unitario");
        iPrecio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iPrecioMouseClicked(evt);
            }
        });
        iPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iPrecioActionPerformed(evt);
            }
        });
        add(iPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 220, 30));
        add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 130, -1));

        jButton3.setBackground(new java.awt.Color(29, 45, 80));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/guardar.png"))); // NOI18N
        jButton3.setText("Crear Insumo");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 150, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(5, 50, 50));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Cantidad : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 220, 37));

        iCantidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iCantidad.setForeground(new java.awt.Color(153, 153, 153));
        iCantidad.setText("Ingrese Existencias");
        iCantidad.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iCantidadMouseClicked(evt);
            }
        });
        iCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iCantidadActionPerformed(evt);
            }
        });
        add(iCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 180, 30));

        combo_tipo.setBackground(new java.awt.Color(252, 249, 249));
        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Tipo de Unidad" }));
        combo_tipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_tipoItemStateChanged(evt);
            }
        });
        add(combo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        edt_otro.setForeground(new java.awt.Color(153, 153, 153));
        edt_otro.setText("Ingrese un Tipo de Unidad");
        edt_otro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edt_otroMouseClicked(evt);
            }
        });
        edt_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edt_otroActionPerformed(evt);
            }
        });
        add(edt_otro, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 160, -1));

        btn_ayuda.setBackground(new java.awt.Color(29, 45, 80));
        btn_ayuda.setForeground(new java.awt.Color(255, 255, 255));
        btn_ayuda.setText("Obtener Precio Unitario");
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });
        add(btn_ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(5, 50, 50));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Nombre del Insumo : ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 190, 37));

        i_minimo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        i_minimo.setForeground(new java.awt.Color(153, 153, 153));
        i_minimo.setText("Ingrese la Cantidad Minima");
        i_minimo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        i_minimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                i_minimoMouseClicked(evt);
            }
        });
        i_minimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_minimoActionPerformed(evt);
            }
        });
        add(i_minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 240, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/question.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        label_ayuda.setBackground(new java.awt.Color(153, 153, 255));
        label_ayuda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        label_ayuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_ayuda.setText("Ayuda");
        label_ayuda.setOpaque(true);
        add(label_ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 260, 90));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear Nuevo Insumo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 340, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        establecerApariencia();
        
        JFileChooser escoger = new JFileChooser();
        escoger.setDialogTitle("Seleccione una Imagen");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        escoger.setFileFilter(filtro);
        
        
             
        
        int b = escoger.showOpenDialog(this);
        if (b == JFileChooser.APPROVE_OPTION) {
            this.jLabel5.setText("");
            String ruta = escoger.getSelectedFile().getAbsolutePath();
            this.ruta.setText(ruta);
            rsscalelabel.RSScaleLabel.setScaleLabel(this.jLabel5, escoger.getSelectedFile().toString());
            
        }
        restablecerApariencia();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void iNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iNombreMouseClicked
        if(con==0){
            con++;
            iNombre.setText("");
        }
    }//GEN-LAST:event_iNombreMouseClicked

    private void iNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iNombreActionPerformed

    private void iPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iPrecioMouseClicked
        if(con5==0){
            con5++;
            iPrecio.setText("");
        }
    }//GEN-LAST:event_iPrecioMouseClicked

    private void iPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iPrecioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String nombre = this.iNombre.getText().toString().trim();
        String cantidad_string = this.iCantidad.getText().toString();
        String descripcion = this.iDescripcion.getText().toString();
        String precio_string = this.iPrecio.getText().toString();
        String tipo_cantidad = this.combo_tipo.getSelectedItem().toString();
        String aux_tipo = this.edt_otro.getText().toString().trim();
        String minimo_string = this.i_minimo.getText().toString().trim();
        File imagen = new File(this.ruta.getText());
        boolean v = false;
        
        
        if (!nombre.equals("Nombre del Insumo") && !nombre.equals("") && !precio_string.equals("Ingrese el Precio Unitario")
                && !precio_string.equals("") && !minimo_string.equals("") && !minimo_string.equals("Ingrese la Cantidad Minima")) {
            if (validarEntero(cantidad_string) && validarEntero(precio_string) && validarEntero(minimo_string)) {
                if (!tipo_cantidad.equals("Seleccione el Tipo de Unidad")) {
                    double cantidad_aux = Double.parseDouble(cantidad_string);
                    double precio = Double.parseDouble(precio_string);
                    double minimo = Double.parseDouble(minimo_string);

                    
                    Insumo i = new Insumo();
                    i.setNombre(nombre);
                    i.setDescripcion(descripcion);
                    i.setCantidad(cantidad_aux);
                    try {
                        byte[] icono = new byte[(int) imagen.length()];
                        InputStream input = new FileInputStream(imagen);
                        input.read(icono);
                        i.setImagen(icono);
                    } catch (Exception ex) {
                        i.setImagen(null);
                    }
                    i.setEstado(true);
                    i.setPrecio(precio);
                    if (tipo_cantidad.equals("Otro...")) {
                        if (!aux_tipo.equals("Ingrese un Tipo de Unidad") && !aux_tipo.isEmpty()) {
                            tipo_cantidad = aux_tipo;
                        } else {
                            JOptionPane.showMessageDialog(null, "Debe ingresar un Tipo de Unidad", "Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                    i.setTipo(tipo_cantidad);

                    Accion a = new Accion();
                    a.setProducto(nombre);
                    a.setDescripcion("Ingreso Nuevo Producto");
                    a.setCantidad(cantidad_aux);
                    a.setUsuario(usuario_iniciado);
                    a.setUltima_cantidad(0);
                    a.setUltimo_precio(precio);

                    Date aux = new Date();
                    System.out.println(aux);
                    String formatoFecha = "hh:mm:ss a dd-MM-yyyy";
                    SimpleDateFormat formato = new SimpleDateFormat(formatoFecha);
                    String f_creacion = formato.format(aux);
                    String fecha = formato.format(aux);
                    System.out.println(formato.format(aux));
                    
                   
                   condicion = minimo;
                    
                    Notificacion n = new Notificacion();
                    n.setCantidadBase(condicion);
                    n.setF_creacion(f_creacion);
                    n.setFecha(fecha);
                    n.setEstado(true);
                    v = MainTransaccion.crearInsumo(i);
                    
                   
                    if (v == true) {
                        MainTransaccion.crearNotificacion(n);

                        MainTransaccion.registrarAccion2(a);
                        System.out.println("SI se creo una notificacion");
                        nuevoInsumo();
                    }
                    
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Debe especificar el tipo de Unidad", "ERROR", JOptionPane.ERROR_MESSAGE);
                }


            } else {
                JOptionPane.showMessageDialog(null, "El campo de Cantidad, Precio e Inventario Minimo, deben ser Numericos", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe llenar el los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        


    }//GEN-LAST:event_jButton3ActionPerformed

    private void iCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iCantidadMouseClicked
        // TODO add your handling code here:
        if(con3 == 0){
            con3++;
            iCantidad.setText("");
        }
    }//GEN-LAST:event_iCantidadMouseClicked

    private void iCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iCantidadActionPerformed

    private void iNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iNombreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_iNombreMouseEntered

    private void combo_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_tipoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            String aux = combo_tipo.getSelectedItem().toString();

            if (combo_tipo.getSelectedItem().toString().equals("Otro...")) {

               edt_otro.setVisible(true);

            } else {
               edt_otro.setVisible(false);

            }

        }
        
    }//GEN-LAST:event_combo_tipoItemStateChanged

    private void edt_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_otroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edt_otroActionPerformed

    private void edt_otroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_otroMouseClicked
        // TODO add your handling code here:
        if(con1 == 0){
            con1++;
            this.edt_otro.setText("");
        }
    }//GEN-LAST:event_edt_otroMouseClicked

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
        
        this.jDialog2.setBounds(0,0,470,350);
        this.jDialog2.setBackground(new Color(252,249,249));
        this.jDialog2.setLocationRelativeTo(this);
        this.jDialog2.setResizable(false);
        this.jDialog2.setVisible(true);
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void btn_aceptar_cadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar_cadaActionPerformed
        // TODO add your handling code here:
        this.txt_p_cada.setText("Precio por cada :");
        this.txt_u_cada.setText("Unidades por cada :");
        this.edt_otro_cada.setText("Especifique");
        this.edt_cada.setText("Ingrese");
        this.edt_precio_cada.setText("Ingrese");
        this.combo_opciones.setSelectedIndex(0);
        this.label_resultado_cada.setText("Resultado");
        
        this.jDialog2.setVisible(false);
        this.jDialog2.dispose();
        this.iPrecio.setText(resultado + "");
    }//GEN-LAST:event_btn_aceptar_cadaActionPerformed

    private void iniciarOpciones(){
        this.combo_opciones.addItem("Paquetes (PAQ)");
        this.combo_opciones.addItem("Cajas");
        this.combo_opciones.addItem("Galones");
        this.combo_opciones.addItem("Quintales");
        this.combo_opciones.addItem("Botellas");
        this.combo_opciones.addItem("Otro...");
        
    }
    private void combo_opcionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_opcionesItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            String aux = combo_opciones.getSelectedItem().toString();
            
            if (!aux.equals("Opciones")) {
                if (combo_opciones.getSelectedItem().toString().equals("Otro...")) {
                   
                    edt_otro_cada.setVisible(true);
                    jDialog2.validate();
                    jDialog2.repaint();
                } else {
                    txt_u_cada.setText("Cantidad por cada " + aux + ": ");
                    txt_p_cada.setText("Precio de cada " + aux + ": ");
                    edt_otro_cada.setVisible(false);
                }
            }else{
                edt_otro_cada.setVisible(false);
            }
            

        }
        
        
    }//GEN-LAST:event_combo_opcionesItemStateChanged

    private void edt_otro_cadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edt_otro_cadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edt_otro_cadaActionPerformed

    private void edt_otro_cadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_otro_cadaMouseClicked
        // TODO add your handling code here:
        if(this.edt_otro_cada.getText().toString().equals("Especifique")){
            this.edt_otro_cada.setText("");
        }
    }//GEN-LAST:event_edt_otro_cadaMouseClicked

    private void edt_cadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_cadaMouseClicked
        // TODO add your handling code here:
        if(this.edt_cada.getText().toString().equals("Ingrese")){
            this.edt_cada.setText("");
        }
    }//GEN-LAST:event_edt_cadaMouseClicked

    private void edt_precio_cadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edt_precio_cadaMouseClicked
        // TODO add your handling code here:
        if(this.edt_precio_cada.getText().toString().equals("Ingrese")){
            this.edt_precio_cada.setText("");
        }
    }//GEN-LAST:event_edt_precio_cadaMouseClicked

    private void btn_calcular_cadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_cadaActionPerformed
        // TODO add your handling code here:
        String cantidad_string = this.edt_cada.getText().toString();
        String precio_string = this.edt_precio_cada.getText().toString();
        
        if (!cantidad_string.equals("") && !precio_string.equals("")) {
            if (validarEntero(cantidad_string) && validarEntero(precio_string)) {
                double cantidad = Double.parseDouble(cantidad_string);
                double precio = Double.parseDouble(precio_string);
                resultado = precio / cantidad;
                
                resultado = (double) Math.round(resultado * 1000d) / 1000d;
            
                this.iPrecio.setText(resultado + "");
                this.label_resultado_cada.setText("Precio Unitario =" + resultado);
            }else{
                JOptionPane.showMessageDialog(null, "La cantidad y el precio deben ser números");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btn_calcular_cadaActionPerformed

    private void nuevoInsumo(){
        this.iNombre.setText("Nombre del Insumo");
        this.iCantidad.setText("Ingrese Existencias");
        this.iPrecio.setText("Ingrese el Precio Unitario");
        this.iDescripcion.setText("");
        this.jLabel5.setIcon(null);
        this.jLabel5.setText("Insertar Imagen");
        this.i_minimo.setText("Ingrese la Cantidad Minima");
        this.ruta.setText("");
    
    }
    
    private void edt_otro_cadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edt_otro_cadaKeyReleased
        // TODO add your handling code here:
        this.txt_u_cada.setText("Unidades por cada " + this.edt_otro_cada.getText());
        this.txt_p_cada.setText("Precio por cada " + this.edt_otro_cada.getText());
    }//GEN-LAST:event_edt_otro_cadaKeyReleased

    private void i_minimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_minimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_minimoActionPerformed

    private void i_minimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_i_minimoMouseClicked
        // TODO add your handling code here:
        if(this.i_minimo.getText().toString().equals("Ingrese la Cantidad Minima")){
            this.i_minimo.setText("");
        }
    }//GEN-LAST:event_i_minimoMouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        this.label_ayuda.setVisible(true);
        this.label_ayuda.setText("<html>" + "<strong>Inventario de Seguridad</strong> <br> Cantidad Minima ha ser mantenida <br>  "
                + "en el Inventario, para que la empresa no <br> detenga su producción" + "</html>");
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        this.label_ayuda.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseExited

    private void label_unidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_unidadMouseEntered
        // TODO add your handling code here:
        l1_unidades.setText("<html>"+"<strong>Unidades:</strong><br> Kilogramos, onzas, <br>litros, unidades, etc"+"</html>");
        l1_unidades.setVisible(true);
        
    }//GEN-LAST:event_label_unidadMouseEntered

    private void label_unidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_unidadMouseExited
        // TODO add your handling code here:
        l1_unidades.setVisible(false);
    }//GEN-LAST:event_label_unidadMouseExited

    private boolean validarEntero(String x){
        try{
            Double.parseDouble(x);
            return true;
        }catch(Exception e){
            return false;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar_cada;
    private javax.swing.JButton btn_ayuda;
    private javax.swing.JButton btn_calcular_cada;
    private javax.swing.JComboBox<String> combo_opciones;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JTextField edt_cada;
    private javax.swing.JTextField edt_otro;
    private javax.swing.JTextField edt_otro_cada;
    private javax.swing.JTextField edt_precio_cada;
    private javax.swing.JTextField iCantidad;
    private javax.swing.JTextArea iDescripcion;
    private javax.swing.JTextField iNombre;
    private javax.swing.JTextField iPrecio;
    private javax.swing.JTextField i_minimo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1_unidades;
    private javax.swing.JLabel label_ayuda;
    private javax.swing.JLabel label_resultado_cada;
    private javax.swing.JLabel label_unidad;
    private javax.swing.JTextField ruta;
    private javax.swing.JLabel txt_p_cada;
    private javax.swing.JLabel txt_u_cada;
    // End of variables declaration//GEN-END:variables
}
