/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insumos;

import clases.Accion;
import clases.MainNotificacion;
import clases.Notificacion;
import clases.Render;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import clases.Insumo;
import clases.MainTransaccion;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static sistema_inventario.Inicio.usuario_iniciado;
import static sistema_inventario.Menu_principal.pantalla1;
import ConexionBDD.Timer1;

/**
 *
 * @author windows
 */
public class E_Insumos extends javax.swing.JPanel {

    /**
     * Creates new form E_Insumos
     */
    int codigo_insumo = 0;
    private String nombre = "";
    
    private Timer1 t = new Timer1();
    
    public E_Insumos() {
        initComponents();
        setPreferredSize(new Dimension(900, 400));
        this.jDialog1.getContentPane().setBackground(new Color(252, 249, 249));
        imprimirElementos(jTable1);
        this.jDialog1.setBounds(0,0,400,320);
        this.jDialog1.setLocationRelativeTo(null);
        this.jDialog1.setResizable(false);
        
    }
    
    private void imprimirElementos(JTable tabla){
        tabla.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        modelo.addColumn("Codigo");
        modelo.addColumn("Insumo");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Imagen");
        
        
        Object[] fila = new Object[modelo.getColumnCount()];
        ArrayList<Insumo> insumos = new ArrayList<Insumo>();
        Insumo insumo = new Insumo();
        insumos = MainTransaccion.insumosEliminados();
        for (int i = 0; i < insumos.size(); i++) {
            insumo = insumos.get(i);
            if (insumo.getEstado() == false) {
                fila[0] = insumo.getId();
                fila[1] = insumo.getNombre();
                fila[2] = insumo.getCantidad();
                try{
                    byte[] bi = insumo.getImagen();
                    BufferedImage image = null;
                    InputStream in = new ByteArrayInputStream(bi);
                    image = ImageIO.read(in);
                    ImageIcon imgi = new ImageIcon(image.getScaledInstance(80, 80, 0));
                    fila[3] = new JLabel(imgi);

                }catch(Exception ex){
                    fila[3] = new JLabel("No imagen");
                }
                
                modelo.addRow(fila);
            }

            tabla.setModel(modelo);
            tabla.setRowHeight(80);
        }
        alinearTabla();    
    
    }
    
    private void alinearTabla(){
        DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        this.jTable1.getColumnModel().getColumn(0).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(1).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(2).setCellRenderer(alinear);
        
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog(pantalla1, "Recuperar Insumo", true);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_confirmacion = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        text_nombre = new javax.swing.JLabel();
        text_codigo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jDialog1.setBackground(new java.awt.Color(252, 249, 249));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Recuperar Insumo");
        jDialog1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 220, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Desea cambiar el estado del Insumo");
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("De: Inactivo -> Activo");
        jDialog1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        btn_confirmacion.setBackground(new java.awt.Color(29, 45, 80));
        btn_confirmacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirmacion.setText("SI");
        btn_confirmacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_confirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmacionActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(btn_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, 40));

        btn_cancelar.setBackground(new java.awt.Color(199, 0, 44));
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("NO");
        btn_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 80, 40));

        text_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        text_nombre.setText("Nombre:");
        jDialog1.getContentPane().add(text_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 220, -1));

        text_codigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_codigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        text_codigo.setText("Codigo:");
        jDialog1.getContentPane().add(text_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 120, -1));

        setBackground(new java.awt.Color(252, 249, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Imagen"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 710, 290));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/aceptar1.png"))); // NOI18N
        jLabel4.setText("Seleccione el Insumo que desea Re-activar");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 370, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        int sRow = this.jTable1.getSelectedRow();
        
        String codigo_aux = modelo.getValueAt(sRow, 0).toString();
        codigo_insumo = Integer.parseInt(codigo_aux);
        
        this.text_codigo.setText("Codigo: " + codigo_aux);
        this.text_nombre.setText("Nombre: " + modelo.getValueAt(sRow, 1).toString());
        nombre = modelo.getValueAt(sRow, 1).toString();
        
        
        
        this.jDialog1.setVisible(true);
              
    }//GEN-LAST:event_jTable1MouseClicked

    
    private void btn_confirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmacionActionPerformed
        // TODO add your handling code here:

        MainTransaccion.activarInsumo(codigo_insumo);
       
        Accion a = new Accion();
        a.setProducto(nombre);
        a.setDescripcion("Reactivacion de Insumo");
        a.setCantidad(0.0);
        a.setUsuario(usuario_iniciado);
        MainTransaccion.registrarAccion(a, codigo_insumo);
        imprimirElementos(jTable1);
        this.jDialog1.dispose();
        
        Prueba p = new Prueba("<html>"+"Se Activo el Insumo<br> Correctamente!"+"</html>");
        p.setVisible(true);             
    }//GEN-LAST:event_btn_confirmacionActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        this.jDialog1.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirmacion;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel text_codigo;
    private javax.swing.JLabel text_nombre;
    // End of variables declaration//GEN-END:variables
}
