/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insumos;

import ConexionBDD.Timer1;
import Proveedores.MainProveedores;
import Proveedores.Proveedor;
import clases.Accion;
import clases.MainNotificacion;
import clases.MainTransaccion;
import clases.Notificacion;
import clases.Render;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static sistema_inventario.Inicio.usuario_iniciado;
import static sistema_inventario.Menu_principal.pantalla1;

/**
 *
 * @author windows
 */
public class E_Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form E_Proveedores
     */
    int codigo_proveedor = 0;
    private String nombre = "";
    
    private Timer1 t = new Timer1();
    
    public E_Proveedores() {
        initComponents();
        setPreferredSize(new Dimension(900, 400));
        
        imprimirDatos(jTable1);
        
        this.jDialog1.getContentPane().setBackground(new Color(252, 249, 249));
        this.jDialog1.setBounds(0,0,400,320);
        this.jDialog1.setLocationRelativeTo(null);
        this.jDialog1.setResizable(false);
        
        
    }

    private void imprimirDatos(JTable tabla){
        tabla.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        modelo.addColumn("Codigo");
        modelo.addColumn("Cedula");
        modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Empresa");
        modelo.addColumn("Email");
        
        Object[] fila = new Object[modelo.getColumnCount()];
        ArrayList<Proveedor> proveedores = new ArrayList<Proveedor>();
        Proveedor p = new Proveedor();
        proveedores = MainProveedores.listaProveedores("WHERE estado_prov = 0");
        for (int i = 0; i < proveedores.size(); i++) {
            p = proveedores.get(i);

            fila[0] = p.getCodigo();
            fila[1] = p.getCedula();
            fila[2] = p.getNombres();
            fila[3] = p.getApellidos();
            fila[4] = p.getEmpresa();
            fila[5] = p.getEmail();
            modelo.addRow(fila);

            tabla.setModel(modelo);
            tabla.setRowHeight(30);
        }
        alinearTabla();
    }
    
    private void alinearTabla(){
        DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        this.jTable1.getColumnModel().getColumn(0).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(1).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(2).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(3).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(4).setCellRenderer(alinear);
        this.jTable1.getColumnModel().getColumn(5).setCellRenderer(alinear);
        
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(5);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog(pantalla1, "Activar Proveedor", true);
        jLabel1 = new javax.swing.JLabel();
        text_ncodigo = new javax.swing.JLabel();
        text_insumo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jDialog1.setBackground(new java.awt.Color(252, 249, 249));
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Activar Proveedor");
        jDialog1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        text_ncodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_ncodigo.setText("Codigo: ");
        jDialog1.getContentPane().add(text_ncodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, -1));

        text_insumo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        text_insumo.setText("Empresa: ");
        jDialog1.getContentPane().add(text_insumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 350, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Desea activar este Proveedor?");
        jDialog1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jButton1.setBackground(new java.awt.Color(29, 45, 80));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SI");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 80, 40));

        jButton2.setBackground(new java.awt.Color(199, 0, 44));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NO");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("De: Inactivo -> Activo");
        jDialog1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        setBackground(new java.awt.Color(252, 249, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cedula", "Nombres", "Apellidos", "Empresa", "Email"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 830, 290));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/aceptar1.png"))); // NOI18N
        jLabel2.setText("Seleccione el Proveedor que desea Re-activar");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 420, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        MainProveedores.cambiarEstadoProveedor(codigo_proveedor, 1);
       
        
//        Accion a = new Accion();
//        a.setProducto(nombre);
//        a.setDescripcion("Reactivacion de Proveedor");
//        a.setCantidad(0.0);
//        a.setUsuario(usuario_iniciado);
//        MainTransaccion.registrarAccion(a, codigo_proveedor);
        
        this.jDialog1.dispose();
        imprimirDatos(jTable1);
        
        Prueba p = new Prueba("<html>" +"Se activo el Proveedor<br> Correctamente"+ "</html>");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jDialog1.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        
        int sRow = this.jTable1.getSelectedRow();
        
        String codigo_aux = modelo.getValueAt(sRow, 0).toString();
        codigo_proveedor = Integer.parseInt(codigo_aux);
        
        this.text_ncodigo.setText("Codigo: " + codigo_proveedor);
        this.text_insumo.setText("Empresa: " + modelo.getValueAt(sRow, 4).toString());
        nombre = modelo.getValueAt(sRow, 1).toString();
        this.jDialog1.setVisible(true);
           
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel text_insumo;
    private javax.swing.JLabel text_ncodigo;
    // End of variables declaration//GEN-END:variables
}
