/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insumos;

import insumos.ListaInsumos;
import clases.Insumo;
import clases.MainReportes;
import clases.MainTransaccion;
import clases.Render;
import clases.ReporteInsumo;
import com.itextpdf.text.Font;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.UIManager;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static sistema_inventario.Inicio.usuario_iniciado;
import static insumos.Pantalla_1.InsumoScroll;
import java.net.URL;
import java.util.Arrays;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import static sistema_inventario.Inicio.tipo_usuario;

/**
 *
 * @author windows
 */
public class Gestion_Reportes extends javax.swing.JPanel {

    /**
     * Creates new form Gestion_Reportes
     */
    String fecha = "";
    private ButtonGroup bg;
    private double t_ingreso = 0, t_retiro = 0, t_costo = 0;
    private String tipo_producto = "";
    private ArrayList<ReporteInsumo> rinsumos;
    private String aux_consulta = "";
    private String aux_fecha = "";
    Grafica g = new Grafica();
    public static String periodo_insumo = "";
    private ArrayList<String> arrayYears;
    private int currentYear = 0;
    
    public Gestion_Reportes() {
        initComponents();
        setBounds(0, 0, 1050, 540);
        contenedor.setPreferredSize(new Dimension(1039, 475));
        setBackground(new Color(252, 249, 249));
        
        arrayYears = new ArrayList<>();
        for (int i=0; i < 10; i++) {
            arrayYears.add(String.valueOf(2020 + i));
            this.combo_year.addItem(String.valueOf(2020 + i));
        }
       
        
        this.btn_tabla.setOpaque(true);
        
        
        if(tipo_usuario.equals("Usuario")){
            this.btn_acciones.setEnabled(false);
        }
        
        combo_dias.setEnabled(false);
        llenarMeses();
        conseguirFecha();
        imprimirProductos(tabla_reportes, "WHERE i.estado = 1 GROUP BY i.id_insumo ORDER BY i.id_insumo");
        
        bg = new ButtonGroup();
        bg.add(u_mayor_costo);
        bg.add(u_menor_costo);
        bg.add(t_mayor_costo);
        bg.add(t_menor_costo);
        
        aux_consulta = "GROUP BY i.id_insumo ORDER BY i.id_insumo";
        
        this.img_suma.setSize(10,10);
        ImageIcon img_1 = new ImageIcon(getClass().getResource("/Imagenes_insumos/suma.png"));
        Icon fondo_1 = new ImageIcon(img_1.getImage().getScaledInstance(this.img_suma.getWidth(), this.img_suma.getHeight(), Image.SCALE_DEFAULT));
        this.img_suma.setIcon(fondo_1);
        
        this.img_resta.setSize(10,7);
        ImageIcon img_2 = new ImageIcon(getClass().getResource("/Imagenes_insumos/resta.png"));
        Icon fondo_2 = new ImageIcon(img_2.getImage().getScaledInstance(this.img_resta.getWidth(), this.img_resta.getHeight(), Image.SCALE_DEFAULT));
        this.img_resta.setIcon(fondo_2);
        
        this.img_imprimir.setSize(50, 50);
        ImageIcon img_3 = new ImageIcon(getClass().getResource("/Imagenes_insumos/imprimir.png"));
        Icon fondo_3 = new ImageIcon(img_3.getImage().getScaledInstance(this.img_imprimir.getWidth(), this.img_imprimir.getHeight(), Image.SCALE_DEFAULT));
        this.img_imprimir.setIcon(fondo_3);
       
        this.contenedor.setBackground(new Color(252,249,249));
       
        llenarProductos();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        contenedor = new javax.swing.JPanel();
        panel_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_acciones = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        combo_productos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total_ingreso = new javax.swing.JLabel();
        total_retiro = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total_costo = new javax.swing.JLabel();
        img_suma = new javax.swing.JLabel();
        img_resta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        u_mayor_costo = new javax.swing.JRadioButton();
        t_mayor_costo = new javax.swing.JRadioButton();
        t_menor_costo = new javax.swing.JRadioButton();
        u_menor_costo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        combo_year = new javax.swing.JComboBox<>();
        combo_meses = new javax.swing.JComboBox<>();
        combo_dias = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_tabla = new javax.swing.JButton();
        btn_grafico = new javax.swing.JButton();
        panel_2 = new javax.swing.JPanel();
        panel_tabla_reporte = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reportes = new javax.swing.JTable();
        btn_imprimir = new javax.swing.JButton();
        img_imprimir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 249, 249));
        setPreferredSize(new java.awt.Dimension(1039, 475));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setPreferredSize(new java.awt.Dimension(1030, 530));

        panel_1.setBackground(new java.awt.Color(252, 249, 249));
        panel_1.setPreferredSize(new java.awt.Dimension(1030, 225));
        panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gestión de Reportes");
        panel_1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, 30));

        btn_acciones.setBackground(new java.awt.Color(29, 45, 80));
        btn_acciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_acciones.setForeground(new java.awt.Color(255, 255, 255));
        btn_acciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/actividad.png"))); // NOI18N
        btn_acciones.setText("Reportes Acciones");
        btn_acciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_acciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accionesActionPerformed(evt);
            }
        });
        panel_1.add(btn_acciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 190, 40));

        jButton3.setBackground(new java.awt.Color(199, 0, 49));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/generar.png"))); // NOI18N
        jButton3.setText("Generar");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 160, 70));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Producto:");
        panel_1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        combo_productos.setBackground(new java.awt.Color(252, 249, 249));
        combo_productos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_productos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los Insumos" }));
        combo_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_productos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_productosItemStateChanged(evt);
            }
        });
        combo_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_productosActionPerformed(evt);
            }
        });
        panel_1.add(combo_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Retiros Totales:");
        panel_1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ingresos Totales:");
        panel_1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        total_ingreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total_ingreso.setText("Ingresos");
        panel_1.add(total_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        total_retiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total_retiro.setText("Retiros");
        panel_1.add(total_retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Costo Total:");
        panel_1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        total_costo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total_costo.setText("Total");
        panel_1.add(total_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        img_suma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_1.add(img_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 40, 40));

        img_resta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_1.add(img_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 30, 20));

        jPanel1.setBackground(new java.awt.Color(29, 45, 80));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ordenar por:");

        u_mayor_costo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        u_mayor_costo.setForeground(new java.awt.Color(255, 255, 255));
        u_mayor_costo.setText("Mayor Costo Unitario");
        u_mayor_costo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u_mayor_costo.setOpaque(false);
        u_mayor_costo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                u_mayor_costoItemStateChanged(evt);
            }
        });
        u_mayor_costo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_mayor_costoMouseClicked(evt);
            }
        });
        u_mayor_costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u_mayor_costoActionPerformed(evt);
            }
        });

        t_mayor_costo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_mayor_costo.setForeground(new java.awt.Color(255, 255, 255));
        t_mayor_costo.setText("Mayor Costo Total");
        t_mayor_costo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_mayor_costo.setOpaque(false);

        t_menor_costo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_menor_costo.setForeground(new java.awt.Color(255, 255, 255));
        t_menor_costo.setText("Menor Costo Total");
        t_menor_costo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t_menor_costo.setOpaque(false);

        u_menor_costo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        u_menor_costo.setForeground(new java.awt.Color(255, 255, 255));
        u_menor_costo.setText("Menor Costo Unitario");
        u_menor_costo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        u_menor_costo.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(u_mayor_costo)
                                .addGap(18, 18, 18)
                                .addComponent(t_mayor_costo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(u_menor_costo)
                                .addGap(18, 18, 18)
                                .addComponent(t_menor_costo)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_mayor_costo)
                    .addComponent(t_mayor_costo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(u_menor_costo)
                    .addComponent(t_menor_costo))
                .addContainerGap())
        );

        panel_1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 44, 330, 90));

        jPanel2.setBackground(new java.awt.Color(209, 18, 50));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton4.setBackground(new java.awt.Color(29, 45, 80));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/calendario2.png"))); // NOI18N
        jButton4.setText("Fecha de Hoy");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        combo_year.setBackground(new java.awt.Color(252, 249, 249));
        combo_year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año" }));
        combo_year.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_yearItemStateChanged(evt);
            }
        });

        combo_meses.setBackground(new java.awt.Color(252, 249, 249));
        combo_meses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes" }));
        combo_meses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_meses.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_mesesItemStateChanged(evt);
            }
        });

        combo_dias.setBackground(new java.awt.Color(252, 249, 249));
        combo_dias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_dias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia" }));
        combo_dias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo_dias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_diasItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(combo_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(combo_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(81, 81, 81))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panel_1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 44, 330, 90));

        btn_tabla.setBackground(new java.awt.Color(49, 99, 241));
        btn_tabla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_tabla.setForeground(new java.awt.Color(255, 255, 255));
        btn_tabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/tabla.png"))); // NOI18N
        btn_tabla.setText("Tabla");
        btn_tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 45, 80)));
        btn_tabla.setContentAreaFilled(false);
        btn_tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tablaActionPerformed(evt);
            }
        });
        panel_1.add(btn_tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 90, 30));

        btn_grafico.setBackground(new java.awt.Color(255, 255, 204));
        btn_grafico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/grafico.png"))); // NOI18N
        btn_grafico.setText("Grafico");
        btn_grafico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 45, 80)));
        btn_grafico.setContentAreaFilled(false);
        btn_grafico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficoActionPerformed(evt);
            }
        });
        panel_1.add(btn_grafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 100, 30));

        contenedor.add(panel_1);

        panel_2.setBackground(new java.awt.Color(252, 249, 249));
        panel_2.setLayout(new java.awt.CardLayout());

        panel_tabla_reporte.setBackground(new java.awt.Color(252, 249, 249));
        panel_tabla_reporte.setPreferredSize(new java.awt.Dimension(1030, 226));

        tabla_reportes.setBackground(new java.awt.Color(252, 249, 249));
        tabla_reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Cantidad", "Descripción", "Costo Unitario", "Costo Total", "Total"
            }
        ));
        tabla_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_reportes.setFocusable(false);
        tabla_reportes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabla_reportes.setRowHeight(25);
        tabla_reportes.setSelectionBackground(new java.awt.Color(209, 18, 50));
        tabla_reportes.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabla_reportes);

        btn_imprimir.setBackground(new java.awt.Color(29, 45, 80));
        btn_imprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_imprimir.setForeground(new java.awt.Color(255, 255, 255));
        btn_imprimir.setText("Imprimir");
        btn_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });

        img_imprimir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Valor del Inventario");

        javax.swing.GroupLayout panel_tabla_reporteLayout = new javax.swing.GroupLayout(panel_tabla_reporte);
        panel_tabla_reporte.setLayout(panel_tabla_reporteLayout);
        panel_tabla_reporteLayout.setHorizontalGroup(
            panel_tabla_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tabla_reporteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panel_tabla_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(img_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(panel_tabla_reporteLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tabla_reporteLayout.setVerticalGroup(
            panel_tabla_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tabla_reporteLayout.createSequentialGroup()
                .addGroup(panel_tabla_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tabla_reporteLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panel_tabla_reporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_tabla_reporteLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btn_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(img_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_tabla_reporteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_2.add(panel_tabla_reporte, "card3");

        contenedor.add(panel_2);

        jScrollPane2.setViewportView(contenedor);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void llenarProductos(){
        ArrayList<Insumo> insumos = new ArrayList<Insumo>();
        Insumo in = new Insumo();
        insumos = MainTransaccion.consultarInsumos("");
        for (int i = 0; i < insumos.size(); i++) {
            in = insumos.get(i);
            if (in.getEstado() == true) {
                this.combo_productos.addItem(in.getId() + "-" + in.getNombre());
            }

        }
             
    }
    
    public void imprimirProductos(JTable tabla, String condicion){
        
        tabla.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel modelo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        
        t_ingreso = 0;
        t_retiro = 0;
        t_costo = 0;
        
        modelo.addColumn("Codigo");
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Retiros");
        modelo.addColumn("Ingresos");
        modelo.addColumn("Total");
        
        if(combo_productos.getSelectedIndex() != 0){
            modelo.addColumn("Fecha");
        }
        
       
        
        Object[] fila = new Object[modelo.getColumnCount()];
        
        ArrayList<ReporteInsumo> insumos = new ArrayList<ReporteInsumo>();
        ReporteInsumo in = new ReporteInsumo();
        insumos = MainReportes.consultarProductos2(condicion);
        for(int i = 0; i < insumos.size(); i++){
            in = insumos.get(i);
            fila[0] = in.getId_insumo();
            fila[1] = in.getNombre();
            fila[2] = in.getCantidad();
            fila[3] = in.getPrecio_unitario();  
            BigDecimal retiro = new BigDecimal(in.getRetiros());
            fila[4] = retiro.setScale(2, RoundingMode.HALF_UP);
            System.out.println("fila retiros: " + fila[4].toString());
            BigDecimal ingreso = new BigDecimal(in.getIngresos());
            fila[5] = ingreso.setScale(2, RoundingMode.HALF_UP);
            BigDecimal total = new BigDecimal(in.getTotal());
            fila[6] = total.setScale(2, RoundingMode.HALF_UP);
            if(combo_productos.getSelectedIndex() != 0){
                fila[7] = in.getFecha();
            }
        
            modelo.addRow(fila);
            
            tabla.setModel(modelo);
            tabla.setRowHeight(30);
            
            
            
            t_ingreso += in.getIngresos();
            t_retiro += in.getRetiros();
            t_costo += in.getTotal();
        }
        
        rinsumos = insumos;
        if(insumos.size() == 0){
            limpiarTabla();
        }
        
        if(combo_productos.getSelectedIndex() == 0){
            periodo_insumo = "";
            g.imprimirGrafico(tabla_reportes, 6, "Costo Total", 0);
        }else{
            periodo_insumo = "Activado";
            g.imprimirGrafico(tabla_reportes, 6, "Costo Total", 7);
            
        }
        
        
        this.total_ingreso.setText(String.format("%.2f", t_ingreso));
        this.total_retiro.setText(String.format("%.2f", t_retiro));
        this.total_costo.setText("$ " + String.format("%.2f", t_costo));
        
      
        alinearTabla();
    }
    
    private void alinearTabla(){
        DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
        alinear.setHorizontalAlignment(SwingConstants.CENTER);
        
        
        this.tabla_reportes.getColumnModel().getColumn(0).setPreferredWidth(10);
        
    }
    
    private void limpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) this.tabla_reportes.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
        
    }
    
    private void establecerApariencia(){
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        }
    }
    private void restablecerApariencia(){
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        } 
    }
    
    
    private void conseguirFecha(){
        Date fecha_defecto = new Date();
        System.out.println(fecha_defecto);
        //String formato_fecha = "hh:mm:ss a dd-MM-yyyy";
        String formato_fecha = "yyyy-MM-dd";
        SimpleDateFormat formato = new SimpleDateFormat(formato_fecha);
        System.out.println(formato.format(fecha_defecto));
        fecha = formato.format(fecha_defecto);
        
    }
    
    private void llenarMeses(){
        String meses[] = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre",
        "Octubre","Noviembre","Diciembre"};
        
        for(int i = 0; i < meses.length; i++){
            combo_meses.addItem(meses[i]);
        }
        
    }
    
    private void llenarDias(String mes, int year){               
        int dias[];
        int cont = 0;
        combo_dias.setEnabled(true);
        combo_dias.removeAllItems();
        combo_dias.addItem("Dia");
        boolean isLeapYear = (currentYear % 4 == 0 && currentYear % 100 != 0) || (currentYear % 400 == 0);
        switch(mes){
            case "Enero":
                cont = 31;             
                break;
            case "Febrero":
                cont = isLeapYear ? 29 : 28;
                break;
            case "Marzo":
                cont = 31;
                break;
            case "Abril":
                cont = 30;               
                break;
            case "Mayo":
                cont = 31;                
                break;
            case "Junio":
                cont = 30;
                
                break;
            case "Julio":
                cont = 31;
                
                break;
            case "Agosto":
                cont = 31;
                
                break;
            case "Septiembre":
                cont = 30;
                
                break;
            case "Octubre":
                cont = 31;
                
                break;
            case "Noviembre":
                cont = 30;
                
                break;
            case "Diciembre":
                cont = 31;
                
                break;       
        }    
        for(int j = 0; j < cont; j++){
            this.combo_dias.addItem(String.valueOf(j+1));
        }
        
    }
    
    public void establecerFecha(){
        String[] fecha_aux = fecha.split("-");
        String aux_year = fecha_aux[2];
        String aux_mes = fecha_aux[1];
        String aux_dia = fecha_aux[0];

        this.combo_year.setSelectedItem(aux_year);
        this.combo_meses.setSelectedIndex(Integer.parseInt(aux_mes));
        this.combo_dias.setSelectedIndex(Integer.parseInt(aux_dia));
    }
    
    
    private void btn_graficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficoActionPerformed
        // TODO add your handling code here:
        this.contenedor.setPreferredSize(new Dimension(1030,830));
        this.panel_tabla_reporte.setVisible(false);
      //  scroll_reporte.setViewportView(g);
        
        panel_2.add(g);
        contenedor.add(panel_2);
        g.setVisible(true);
        
        this.btn_grafico.setEnabled(false);
        this.btn_tabla.setEnabled(true);
        
        this.btn_grafico.setOpaque(true);
        this.btn_grafico.setBackground(new Color(49,99,241));
        this.btn_grafico.setForeground(new Color(255, 255, 255));
        
        this.btn_tabla.setBackground(new Color(252, 249, 249));
        this.btn_tabla.setForeground(new Color(0, 0, 0));
        
        
    }//GEN-LAST:event_btn_graficoActionPerformed

    private void btn_tablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tablaActionPerformed
        // TODO add your handling code here:

        //scroll_reporte.getViewport().remove(g);
        //scroll_reporte.updateUI();
        this.btn_tabla.setOpaque(true);
        this.btn_tabla.setBackground(new Color(49, 99, 241));
        this.btn_tabla.setForeground(new Color(255, 255, 255));
        
        this.btn_grafico.setBackground(new Color(252, 249, 249));
        this.btn_grafico.setForeground(new Color(0, 0, 0));
        
        this.contenedor.setPreferredSize(new Dimension(1030,530));
        g.setVisible(false);
        
        this.panel_tabla_reporte.setVisible(true);
        //scroll_reporte.setViewportView(this.panel_tabla_reporte);
        this.btn_tabla.setEnabled(false);
        this.btn_grafico.setEnabled(true);
    }//GEN-LAST:event_btn_tablaActionPerformed

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        // TODO add your handling code here:

        if(this.combo_year.getSelectedItem().toString().equals("Año")){
            aux_fecha = fecha;
        }
        String[] auxiliar = aux_fecha.split("-");
        String year = "No Seleccionado", mes = "No Seleccionado", dia = "No Seleccionado";
        for(int i = 0; i<auxiliar.length; i++){
            if(i == 0){
                year = auxiliar[i];
            }else if(i == 1){
                mes = auxiliar[i];
            }else if(i == 2){
                dia = auxiliar[i];
            }

        }
        System.out.println("Tamanio de la fecha = " + auxiliar.length);
        System.out.println("Fecha enviada -> " + "YEar: " +year+"MES:"+mes+"Dia:"+dia);

        ArrayList<String> parametros = new ArrayList<String>();
        parametros.add(usuario_iniciado);
        parametros.add(this.total_retiro.getText().toString());
        parametros.add(this.total_ingreso.getText().toString());
        parametros.add(this.total_costo.getText().toString());
        parametros.add(year);
        parametros.add(mes);
        parametros.add(dia);

        //String path1 = System.getProperty("user.dir") + "\\src\\Reportes\\Reporte1.jasper";
        URL path1 = this.getClass().getResource("/Reportes/Reporte1.jasper");
        //String path1 = "src\\Reportes\\Reporte1.jasper";
        System.out.println("Direccion //// " + path1);
        System.out.println("Direccion //// " + path1 + "df");
        // src\\Reportes\\Reporte1.jasper
        //String path1 = "C:\\Users\\windows\\Desktop\\Practica Java\\Respaldos\\recta_final_04_01_2021\\13_12_2020\\Sistema_Inventario\\src\\Reportes\\Reporte1.jasper";
        System.out.println("Consulta enviada ---> " + aux_consulta);
        MainReportes.realizarConsulta(path1, aux_consulta, parametros);
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void combo_diasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_diasItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            String aux = combo_dias.getSelectedItem().toString();
            if(!combo_dias.getSelectedItem().toString().equals("Dia")){

            }
        }
    }//GEN-LAST:event_combo_diasItemStateChanged

    private void combo_mesesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_mesesItemStateChanged
        // TODO add your handling code here:

        if(evt.getStateChange() == ItemEvent.SELECTED){
            String aux = evt.getItem().toString();
            if(!evt.getItem().toString().equals("Mes") && !this.combo_year.getSelectedItem().toString().equals("Año")){
                String y_string = this.combo_year.getSelectedItem().toString();
                int y = Integer.parseInt(y_string);
                llenarDias(aux, y);
            }else{
                combo_dias.removeAllItems();
                combo_dias.addItem("Dia");
            }
        }
    }//GEN-LAST:event_combo_mesesItemStateChanged

    private void combo_yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_yearItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.combo_meses.setSelectedItem("Mes");
            currentYear = Integer.valueOf(evt.getItem().toString());
        }
    }//GEN-LAST:event_combo_yearItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // * PONER LA FECHA DE HOY *
        String[] fecha_aux = fecha.split("-");
        String aux_year = fecha_aux[0];
        String aux_mes = fecha_aux[1];
        String aux_dia = fecha_aux[2];
        if (arrayYears.contains(aux_year)) {
            this.combo_year.setSelectedItem(aux_year);
        } else {
            arrayYears.add(aux_year);
            this.combo_year.addItem(aux_year);
            this.combo_year.setSelectedItem(aux_year);
        }
        
        this.combo_meses.setSelectedIndex(Integer.parseInt(aux_mes));
        this.combo_dias.setSelectedIndex(Integer.parseInt(aux_dia));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void u_mayor_costoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u_mayor_costoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_u_mayor_costoActionPerformed

    private void u_mayor_costoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_mayor_costoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_u_mayor_costoMouseClicked

    private void u_mayor_costoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_u_mayor_costoItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_u_mayor_costoItemStateChanged

    private void combo_productosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_productosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            String aux = combo_productos.getSelectedItem().toString();

            if (!combo_productos.getSelectedItem().toString().equals("Todos los Insumos")) {

                /* Combo de como podemos hacer esto*/
                String[] partes = aux.split("-");

                String nombre = partes[1];
                int codigo = Integer.parseInt(partes[0]);
                //imprimirProductos(tabla_reportes, "WHERE i.id_insumo = " + codigo);
                //Desde aqui esta lo agregado
                generarConsulta(codigo);

            } else {
                //imprimirProductos(tabla_reportes, "GROUP BY i.id_insumo");

            }

        }

    }//GEN-LAST:event_combo_productosItemStateChanged

    private void generarConsulta(int x){
        String condicion = "";
        String year = this.combo_year.getSelectedItem().toString();
        String mes_string = this.combo_meses. getSelectedItem().toString();
        String dia = this.combo_dias.getSelectedItem().toString();
        String ordenar = "";

        if(u_mayor_costo.isSelected() == true){
            ordenar = "ORDER BY i.precio_unitario desc";

        }else if(u_menor_costo.isSelected() == true){
            ordenar = "ORDER BY i.precio_unitario asc";
        }else if(t_mayor_costo.isSelected() == true){
            ordenar = "ORDER BY Calculo desc";
        }else if(t_menor_costo.isSelected() == true){
            ordenar = "ORDER BY Calculo asc";
        }else{
            ordenar = "ORDER BY i.id_insumo";
        }
        

        if(!year.equals("Año")){
            condicion = "WHERE year(a.fecha_accion) = " + year;
            aux_fecha = year;
            if(!mes_string.equals("Mes")){
                condicion += " and month(a.fecha_accion) = " + this.combo_meses.getSelectedIndex();
                aux_fecha += "-" + mes_string;
                if(!dia.equals("Dia")){
                    condicion += " and day(a.fecha_accion) = " + dia;
                    aux_fecha += "-" + dia;
                }
            }
            
            if(x == 0){
                imprimirProductos(tabla_reportes, condicion + " and i.estado = 1 " + " GROUP BY i.id_insumo " + ordenar);
                aux_consulta = condicion + " and i.estado = 1 " + " GROUP BY i.id_insumo " + ordenar;
            }else{
                System.out.println("Enviado desde el combo box");
                imprimirProductos(tabla_reportes, condicion + " and i.estado = 1 " + " and i.id_insumo = " + x + " "
                        + "GROUP BY year(a.fecha_accion), month(a.fecha_accion), day(a.fecha_accion) " + ordenar);
                aux_consulta = condicion + " and i.estado = 1 " + " and i.id_insumo = " + x + " GROUP BY year(a.fecha_accion), "
                        + "month(a.fecha_accion), day(a.fecha_accion) " + ordenar;
            }
            
        }else{
            if(x == 0){
                imprimirProductos(tabla_reportes, "WHERE i.estado = 1 " + " GROUP BY i.id_insumo " + ordenar);
                aux_consulta = "WHERE i.estado = 1 " + " GROUP BY i.id_insumo " + ordenar;
            }else{
                System.out.println("Enviar desde el combo box 2");
                imprimirProductos(tabla_reportes, "WHERE i.id_insumo = " + x + " and i.estado = 1 " + " GROUP BY year(a.fecha_accion), "
                        + "month(a.fecha_accion), day(a.fecha_accion) " + ordenar);
                aux_consulta = "WHERE i.id_insumo = " + x + " and i.estado = 1 " + "GROUP BY year(a.fecha_accion), month(a.fecha_accion), "
                        + "day(a.fecha_accion) " + ordenar;
            }
            
        }

        
        System.out.println("Consulta antes del error -> " + aux_consulta);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //this.combo_productos.setSelectedIndex(0);
        
        int codigo = this.combo_productos.getSelectedIndex();
        if(codigo == 0){
            generarConsulta(0);
        }else{
            String aux_string = this.combo_productos.getSelectedItem().toString();
            String[] partes = aux_string.split("-");
            int a = Integer.parseInt(partes[0]);
            generarConsulta(a);
        }
                              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_accionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accionesActionPerformed
        // TODO add your handling code here:
        Reporte r = new Reporte();
        InsumoScroll.remove(this);
        InsumoScroll.setViewportView(r);
    }//GEN-LAST:event_btn_accionesActionPerformed

    private void combo_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_productosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acciones;
    private javax.swing.JButton btn_grafico;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combo_dias;
    private javax.swing.JComboBox<String> combo_meses;
    private javax.swing.JComboBox<String> combo_productos;
    private javax.swing.JComboBox<String> combo_year;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel img_imprimir;
    private javax.swing.JLabel img_resta;
    private javax.swing.JLabel img_suma;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JPanel panel_tabla_reporte;
    private javax.swing.JRadioButton t_mayor_costo;
    private javax.swing.JRadioButton t_menor_costo;
    private javax.swing.JTable tabla_reportes;
    private javax.swing.JLabel total_costo;
    private javax.swing.JLabel total_ingreso;
    private javax.swing.JLabel total_retiro;
    private javax.swing.JRadioButton u_mayor_costo;
    private javax.swing.JRadioButton u_menor_costo;
    // End of variables declaration//GEN-END:variables
}
