/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package insumos;

import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JTable;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import static insumos.Gestion_Reportes.periodo_insumo;
import javafx.scene.chart.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;

/**
 *
 * @author windows
 */
public class Grafica extends javax.swing.JPanel {

    /**
     * Creates new form Grafica
     */
    
    private ButtonGroup bg;
    private JTable tabla_auxiliar;
    private DefaultCategoryDataset dcds;
    private JFreeChart ch;
    private ChartPanel cp;
    private String recibido = "";
    
    public Grafica() {
        initComponents();
        setPreferredSize(new Dimension(1030, 800));
        setBounds(30,30,1030,800);
        bg = new ButtonGroup();
        bg.add(c_ingreso);
        bg.add(c_retiro);
        bg.add(c_unitario);
        bg.add(c_total);
        
        this.c_total.setSelected(true);
        
        iniciarGrafico();
    }
    
    public void iniciarGrafico(){
        dcds = new DefaultCategoryDataset();
        for(int i = 0; i < 5; i++){
            dcds.setValue(i, "Titulo", "Prueba");
        }
        ch = ChartFactory.createBarChart3D("Grafico Inicializado","Como estas", "Prueba", dcds, PlotOrientation.VERTICAL, true, true, false);
        cp = new ChartPanel(ch);
        add(cp);
        cp.setBounds(30, 80, 800, 400);
        cp.updateUI();
    }
    
    public void imprimirGrafico(JTable tabla, int x, String tipo, int y){
        recibido = periodo_insumo;
        System.out.println("Mensajes>>>> " + recibido);
        if(x == 6){
            this.c_total.setSelected(true);
        }
        tabla_auxiliar = tabla;       
        remove(cp);
        dcds = new DefaultCategoryDataset();
              
        for(int i = 0; i < tabla.getRowCount(); i++){     
            dcds.setValue(Double.parseDouble(tabla.getValueAt(i, x).toString()), tabla.getValueAt(i, 1).toString(), tabla.getValueAt(i, y).toString());
        }
   
        
        ch = ChartFactory.createBarChart3D("Grafico creado", "Identificador", tipo, dcds, PlotOrientation.VERTICAL, true, true, false);  
        cp = new ChartPanel(ch);
        add(cp);
        cp.setBounds(120,60,800,400);
        cp.updateUI();
        
        this.cp.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        c_ingreso = new javax.swing.JCheckBox();
        c_retiro = new javax.swing.JCheckBox();
        c_unitario = new javax.swing.JCheckBox();
        c_total = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(29, 45, 80));

        jPanel1.setBackground(new java.awt.Color(209, 18, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Parametros:");

        c_ingreso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_ingreso.setForeground(new java.awt.Color(255, 255, 255));
        c_ingreso.setText("Ingresos");
        c_ingreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_ingreso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c_ingresoItemStateChanged(evt);
            }
        });
        c_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ingresoActionPerformed(evt);
            }
        });

        c_retiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_retiro.setForeground(new java.awt.Color(255, 255, 255));
        c_retiro.setText("Retiros");
        c_retiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_retiroActionPerformed(evt);
            }
        });

        c_unitario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_unitario.setForeground(new java.awt.Color(255, 255, 255));
        c_unitario.setText("Precio Unitario");
        c_unitario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_unitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_unitarioActionPerformed(evt);
            }
        });

        c_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c_total.setForeground(new java.awt.Color(255, 255, 255));
        c_total.setText("Costo Total");
        c_total.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(c_ingreso)
                .addGap(18, 18, 18)
                .addComponent(c_retiro)
                .addGap(18, 18, 18)
                .addComponent(c_unitario)
                .addGap(18, 18, 18)
                .addComponent(c_total)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_ingreso)
                    .addComponent(c_retiro)
                    .addComponent(c_unitario)
                    .addComponent(c_total)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void c_ingresoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c_ingresoItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_c_ingresoItemStateChanged

    private void c_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ingresoActionPerformed
        // TODO add your handling code here:
       remove(cp);
       if(recibido.equals("")){
           imprimirGrafico(tabla_auxiliar, 5, "Ingresos", 0);
       }else{
           imprimirGrafico(tabla_auxiliar, 5, "Ingresos", 7);
       }
       
       
    }//GEN-LAST:event_c_ingresoActionPerformed

    private void c_retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_retiroActionPerformed
        // TODO add your handling code here:
        remove(cp);
        if(recibido.equals("")){
            imprimirGrafico(tabla_auxiliar, 4, "Retiros", 0);
        }else{
            imprimirGrafico(tabla_auxiliar, 4, "Retiros", 7);
        }
        
    }//GEN-LAST:event_c_retiroActionPerformed

    private void c_unitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_unitarioActionPerformed
        // TODO add your handling code here:
        remove(cp);
        if(recibido.equals("")){
            imprimirGrafico(tabla_auxiliar, 3, "Precio", 0);
        }else{
            imprimirGrafico(tabla_auxiliar, 3, "Precio", 7);
        }
        
    }//GEN-LAST:event_c_unitarioActionPerformed

    private void c_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_totalActionPerformed
        // TODO add your handling code here:
        remove(cp);
        if(recibido.equals("")){
            imprimirGrafico(tabla_auxiliar, 6, "Costo Total", 0);
        }else{
            imprimirGrafico(tabla_auxiliar, 6, "Costo Total", 7);
        }
        
    }//GEN-LAST:event_c_totalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c_ingreso;
    private javax.swing.JCheckBox c_retiro;
    private javax.swing.JCheckBox c_total;
    private javax.swing.JCheckBox c_unitario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
