package insumos;
import insumos.ListaInsumos;
import clases.Insumo;
import clases.MainTransaccion;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import sistema_inventario.Inicio;
import static sistema_inventario.Inicio.tipo_usuario;
import sistema_inventario.Menu_principal;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

/**
 *
 * @author intel
 */
public class Pantalla_1 extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_1
     */
    // Esta es la ultima version
    public static String texto = "", imagen = ""; 
    public static int codigo = 0;
    public static int fundas = 60;
    public static String[] insumos = {"fundas","acido nitrico","cloruro calcio","sosa caustica","sal grano","sal refinada"};
    public static String[] img_insumos = {"fundas.jpg","acido_nitrico.jpg","cloruro_calcio.jpg","sosa_caustica.jpg",
                                         "sal_grano.jpg","sal_refinada.jpg"};
    
    private JLabel l1, l2;
    private JScrollPane scroll;
    private JPanel panel;
    
    private List<JButton> botones;
    private int indice;
    
    private List<JLabel> imagenes;
    
    Border border = BorderFactory.createLineBorder(Color.black, 1);
    
    
    public Pantalla_1() {
        initComponents();
        getContentPane().setBackground(new Color(252,249,249));
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes_insumos/sello_prolase.png")).getImage());
        setBounds(0,0,1050,600);
        setResizable(false);
        setLocationRelativeTo(null);
        
       botones = new ArrayList<>();
       indice = 0;
        
        imagenes = new ArrayList<>();
        restablecerApariencia();
        btn_eliminados.setHorizontalAlignment(SwingConstants.CENTER);
      
       if(tipo_usuario.equals("Usuario")){
           btn_eliminados.setVisible(false);
           btn_notificaciones.setVisible(false);
       }
       /* 
        ImageIcon img_1 = new ImageIcon(getClass().getResource("/Imagenes/fundas.jpg"));
        Icon fondo_1 = new ImageIcon(img_1.getImage().getScaledInstance(this.img_fundas.getWidth(), this.img_fundas.getHeight(), Image.SCALE_DEFAULT));
        this.img_fundas.setIcon(fondo_1);
        
      
        
        ImageIcon img_3 = new ImageIcon(getClass().getResource("/Imagenes/cloruro_calcio.jpg"));
        Icon fondo_3 = new ImageIcon(img_3.getImage().getScaledInstance(this.img_calcio.getWidth(), this.img_calcio.getHeight(), Image.SCALE_DEFAULT));
        this.img_calcio.setIcon(fondo_3);
        
        */
       ListaInsumos l = new ListaInsumos();
       InsumoScroll.setViewportView(l);
       this.btn_inicio.setBackground(new Color(199,0,49));
       this.btn_inicio.setForeground(Color.white);
           
    }
   
  

    private void restablecerApariencia(){
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            // If Nimbus is not available, you can set the GUI to another look and feel.
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_config1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InsumoScroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        btn_reportes = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_notificaciones = new javax.swing.JButton();
        btn_inicio = new javax.swing.JButton();
        btn_eliminados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_config1.setBackground(new java.awt.Color(252, 249, 249));
        panel_config1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PROLASEa.png"))); // NOI18N
        panel_config1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(5, 50, 50));
        jLabel19.setText("Sistema de Gestion de Inventario-Insumos");
        panel_config1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 390, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 40, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 30));

        getContentPane().add(panel_config1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1048, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        InsumoScroll.setViewportView(jPanel1);

        getContentPane().add(InsumoScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1050, 490));

        panel_menu.setBackground(new java.awt.Color(252, 249, 249));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reportes.setBackground(new java.awt.Color(252, 249, 249));
        btn_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/reportes.png"))); // NOI18N
        btn_reportes.setText("Reportes");
        btn_reportes.setBorder(null);
        btn_reportes.setContentAreaFilled(false);
        btn_reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_reportes.setOpaque(true);
        btn_reportes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/reporte48.png"))); // NOI18N
        btn_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_reportesMouseExited(evt);
            }
        });
        btn_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportesActionPerformed(evt);
            }
        });
        panel_menu.add(btn_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, 50));

        btn_nuevo.setBackground(new java.awt.Color(252, 249, 249));
        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/registrar.png"))); // NOI18N
        btn_nuevo.setText("Nuevo Insumo");
        btn_nuevo.setBorder(null);
        btn_nuevo.setContentAreaFilled(false);
        btn_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nuevo.setOpaque(true);
        btn_nuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/nuevo48.png"))); // NOI18N
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseExited(evt);
            }
        });
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        panel_menu.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 130, 50));

        jButton2.setBackground(new java.awt.Color(252, 249, 249));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/flecha32.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/flecha48.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        panel_menu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 50));

        btn_notificaciones.setBackground(new java.awt.Color(252, 249, 249));
        btn_notificaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_notificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/notificaciones.png"))); // NOI18N
        btn_notificaciones.setText("Notificaciones");
        btn_notificaciones.setContentAreaFilled(false);
        btn_notificaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_notificaciones.setOpaque(true);
        btn_notificaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/notificacion48.png"))); // NOI18N
        btn_notificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_notificacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_notificacionesMouseExited(evt);
            }
        });
        btn_notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notificacionesActionPerformed(evt);
            }
        });
        panel_menu.add(btn_notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 160, 50));

        btn_inicio.setBackground(new java.awt.Color(252, 249, 249));
        btn_inicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/home32.png"))); // NOI18N
        btn_inicio.setText("Actualizar");
        btn_inicio.setContentAreaFilled(false);
        btn_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_inicio.setOpaque(true);
        btn_inicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/home48.png"))); // NOI18N
        btn_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_inicioMouseExited(evt);
            }
        });
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        panel_menu.add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 130, 50));

        btn_eliminados.setBackground(new java.awt.Color(252, 249, 249));
        btn_eliminados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/borrados.png"))); // NOI18N
        btn_eliminados.setText("<html>"+"Elementos<br>eliminados"+"</html>");
        btn_eliminados.setContentAreaFilled(false);
        btn_eliminados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminados.setOpaque(true);
        btn_eliminados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/borrador48.png"))); // NOI18N
        btn_eliminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminadosMouseClicked(evt);
            }
        });
        panel_menu.add(btn_eliminados, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 150, 50));

        getContentPane().add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1050, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void limpiarBotones(){
        Component[] com = panel_menu.getComponents();
        for(int i = 0; i < com.length; i++){
            if(com[i] instanceof JButton){
                JButton boton = (JButton) com[i];
                boton.setBackground(new Color(252, 249, 249));
                boton.setForeground(Color.black);
            }
        }
    }
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Desea Salir del Programa","Exit",dialog);
        if(result== 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void btn_reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportesMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_reportesMouseEntered

    private void btn_reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_reportesMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_reportesMouseExited

    private void btn_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportesActionPerformed
        // TODO add your handling code here:
        Gestion_Reportes g = new Gestion_Reportes();
        InsumoScroll.remove(this);
        InsumoScroll.setViewportView(g);
        limpiarBotones();
        this.btn_reportes.setBackground(new Color(199, 0 ,49));
        this.btn_reportes.setForeground(Color.white);
    }//GEN-LAST:event_btn_reportesActionPerformed

    private void btn_nuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_nuevoMouseEntered

    private void btn_nuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_nuevoMouseExited

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        Crear c = new Crear();
        InsumoScroll.remove(this);
        InsumoScroll.setViewportView(c);
        limpiarBotones();
        this.btn_nuevo.setBackground(new Color(199, 0, 49));
        this.btn_nuevo.setForeground(Color.white);
        //
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Menu_principal m = new Menu_principal();
        m.setVisible(true);
        this.setVisible(false);
        //((JFrame) SwingUtilities.getWindowAncestor(this)).dispose();

    }//GEN-LAST:event_jButton2MouseClicked

    private void btn_notificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notificacionesActionPerformed
        // TODO add your handling code here:
        ListaNotificaciones ln = new ListaNotificaciones();
        InsumoScroll.remove(this);
        InsumoScroll.setViewportView(ln);
        limpiarBotones();
        this.btn_notificaciones.setBackground(new Color(199,0,49));
        this.btn_notificaciones.setForeground(Color.white);
        
    }//GEN-LAST:event_btn_notificacionesActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_inicioMouseEntered

    private void btn_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_inicioMouseExited

    private void btn_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inicioMouseClicked
        // TODO add your handling code here:
        ListaInsumos l = new ListaInsumos();
        InsumoScroll.remove(this);
        InsumoScroll.setViewportView(l);
        limpiarBotones();
        this.btn_inicio.setBackground(new Color(199,0,49));
        this.btn_inicio.setForeground(Color.white);
    }//GEN-LAST:event_btn_inicioMouseClicked

    private void btn_notificacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notificacionesMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_notificacionesMouseEntered

    private void btn_notificacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_notificacionesMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_notificacionesMouseExited

    private void btn_eliminadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminadosMouseClicked
        // TODO add your handling code here:
        Eliminados e = new Eliminados();
        InsumoScroll.remove(this);
        InsumoScroll.setViewportView(e);
        limpiarBotones();
        this.btn_eliminados.setBackground(new Color(199,0,49));
        this.btn_eliminados.setForeground(Color.white);
    }//GEN-LAST:event_btn_eliminadosMouseClicked

    
    // COMENTAR/DESCOMENTAR PARA PROBAR todo este metodo
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {;;
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pantalla_1().setVisible(true);
////                try {                   
////                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
////                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
////                    Logger.getLogger(Pantalla_1.class.getName()).log(Level.SEVERE, null, ex);
////                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane InsumoScroll;
    private javax.swing.JButton btn_eliminados;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_notificaciones;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_reportes;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_config1;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
