/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_inventario;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class alertas extends javax.swing.JPanel {
int con =0;
    /**
     * Creates new form alertas
     */
    public alertas() {
        
        initComponents();
         combo_tipo.addItem("Administrador");
         combo_tipo.addItem("Usuario");
        String  txt_nombre="";
      


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_confirmacion = new javax.swing.JPasswordField();
        txt_email = new javax.swing.JTextField();
        combo_tipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N

        setBackground(new java.awt.Color(252, 249, 249));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setForeground(new java.awt.Color(5, 50, 50));
        jButton4.setText("Guardar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 80, 30));

        jButton5.setForeground(new java.awt.Color(5, 50, 50));
        jButton5.setText("Cancelar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 80, 30));

        txt_nombre.setBackground(new java.awt.Color(102, 102, 102));
        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setText("  Ingrese Nombre ");
        txt_nombre.setBorder(null);
        txt_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_nombreMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombreMousePressed(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, 30));

        txt_apellido.setBackground(new java.awt.Color(102, 102, 102));
        txt_apellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setText("  Ingrese Apellido");
        txt_apellido.setBorder(null);
        txt_apellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_apellidoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_apellidoMousePressed(evt);
            }
        });
        txt_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellidoActionPerformed(evt);
            }
        });
        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 170, 30));

        txt_password.setBackground(new java.awt.Color(102, 102, 102));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setText("jPasswordField1");
        txt_password.setBorder(null);
        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passwordMousePressed(evt);
            }
        });
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, 30));

        txt_confirmacion.setBackground(new java.awt.Color(102, 102, 102));
        txt_confirmacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_confirmacion.setText("jPasswordField1");
        txt_confirmacion.setBorder(null);
        txt_confirmacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_confirmacionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_confirmacionMousePressed(evt);
            }
        });
        txt_confirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_confirmacionActionPerformed(evt);
            }
        });
        add(txt_confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 170, 30));

        txt_email.setBackground(new java.awt.Color(102, 102, 102));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setText("  Correo Electronico");
        txt_email.setBorder(null);
        txt_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_emailMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_emailMousePressed(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 170, 30));

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });
        add(combo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 170, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, 160));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(5, 50, 50));
        jLabel9.setText("Nombre:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(5, 50, 50));
        jLabel10.setText("Apellido:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(5, 50, 50));
        jLabel11.setText("Contraseña:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(5, 50, 50));
        jLabel13.setText("Repita Contraseña:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 150, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(5, 50, 50));
        jLabel12.setText("Correo Electronico: ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 180, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 50, 50));
        jLabel2.setText("Tipo de Usuario");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 120, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/fondologo.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, -40, 810, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreMouseClicked

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
    
      
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_apellidoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoMouseClicked

    private void txt_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellidoActionPerformed

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        txt_password.setText("");
    }//GEN-LAST:event_txt_passwordMouseClicked

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_confirmacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_confirmacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_confirmacionMouseClicked

    private void txt_confirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_confirmacionActionPerformed
       txt_confirmacion.setText("");
    }//GEN-LAST:event_txt_confirmacionActionPerformed

    private void txt_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMouseClicked
        txt_email.setText("");
    }//GEN-LAST:event_txt_emailMouseClicked

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String nombre = this.txt_nombre.getText().trim();
        String apellido = this.txt_apellido.getText().trim();
        String password = new String(this.txt_password.getPassword());
        String confirmacion = new String(this.txt_confirmacion.getPassword());
        String email = this.txt_email.getText().trim();
        String tipo = this.combo_tipo.getSelectedItem().toString();

        if(!nombre.equals("") && !apellido.equals("") && !password.equals("") && !confirmacion.equals("")
            && !email.equals("") && !tipo.equals("Seleccione")){
            if(password.equals(confirmacion)){
                Usuario u = new Usuario();
                u.setNombre(nombre);
                u.setApellido(apellido);
                u.setPassword(password);
                u.setEmail(email);
                u.setTipo(tipo);
                u.setEstado(true);
                MainInicio.registrarUsuario(u);
            }else{
                JOptionPane.showMessageDialog(null, "Los passwords no coinciden");
            }

        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_password.setText("");
        txt_confirmacion.setText("");
         txt_email.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
  
    }//GEN-LAST:event_jButton5MouseClicked

    private void txt_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMousePressed
  txt_nombre.setText("");
    }//GEN-LAST:event_txt_nombreMousePressed

    private void txt_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_apellidoMousePressed
 txt_apellido.setText("");
    }//GEN-LAST:event_txt_apellidoMousePressed

    private void txt_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMousePressed
       txt_password.setText("");
    }//GEN-LAST:event_txt_passwordMousePressed

    private void txt_confirmacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_confirmacionMousePressed
  txt_confirmacion.setText("");
    }//GEN-LAST:event_txt_confirmacionMousePressed

    private void txt_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_emailMousePressed
     txt_email.setText("");
    }//GEN-LAST:event_txt_emailMousePressed

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed

//        String password2;
//        String password =JOptionPane.showInputDialog(null,"Ingrese contraseña Administrador");
//      password2 = "PROLASE";
//          
//     if(password == null ? password2 == null : password.equals(password2)){
//         combo_tipo.requestFocus();
//             JOptionPane.showMessageDialog(null, "contraseña buena "); 
//              jButton4.setEnabled(true);
//     } else {                
//                JOptionPane.showMessageDialog(null, "contraseña incorrecta ");
//                  
//                    
//                  txt_confirmacion.setText("");
//                  jButton4.setEnabled(false);
//            }
        
              
    }//GEN-LAST:event_combo_tipoActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_apellidoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JPasswordField txt_confirmacion;
    public javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
