/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_inventario;

import ConexionBDD.Conexion;
import ConexionBDD.Timer1;
import insumos.Prueba;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sistema_inventario.modificar_usuario.pat;

/**
 *
 * @author windows
 */
public class E_Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form E_Usuarios
     */
    
    private Timer1 t = new Timer1();
    
    public static PreparedStatement pat;

    
    Statement st;
    ResultSet rs;
    
    private String nombre = "";
    
    public E_Usuarios() {
        initComponents();
        
        
    }

    public void imprimirEliminados(){
        t.iniciar1();
        Conexion cc = new Conexion();
        Connection con = cc.getConnection();            
        String[] titulos = {" Nombre ", "  Tipo "};
        String[] registros = new String[2];

        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        String SQL = "SELECT * FROM usuario WHERE estado_usuario = 0";

        try {

            st = con.createStatement();
            rs = st.executeQuery(SQL);

            while (rs.next()) {
                registros[0] = rs.getString("nombre_usuario");
                registros[1] = rs.getString("tipo_usuario");

                modelo.addRow(registros);
            }
            tabla_ueliminados.setModel(modelo);
            tabla_ueliminados.setRowHeight(30);
            con.close();
            t.pausar("Imprimir Eliminados");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de acceso " + e.getMessage());
        }
    }
    
    
    private void reactivarUsuario(){
        t.iniciar1();
        Conexion cc = new Conexion();
        Connection con = cc.getConnection();
        
        try {
            con = cc.getConnection();
            pat = con.prepareStatement("UPDATE usuario SET estado_usuario = 1 "
                    + "WHERE nombre_usuario = ?");
            pat.setString(1, nombre);

            int res = pat.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Se Reactivo el Usuario");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Recuperar al Usuario");
            }
            con.close();
            t.pausar("Reactivar Usuario");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tipo : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_ueliminados = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(252, 249, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 160, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuarios Eliminados");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 410, 30));

        tabla_ueliminados.setBackground(new java.awt.Color(255, 102, 0));
        tabla_ueliminados.setForeground(new java.awt.Color(255, 255, 255));
        tabla_ueliminados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ));
        tabla_ueliminados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla_ueliminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_ueliminadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla_ueliminados);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 190));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_insumos/aceptar1.png"))); // NOI18N
        jLabel4.setText("Seleccione el Usuario que desea Reactivar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 320, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/fondologo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 850, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_ueliminadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_ueliminadosMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.tabla_ueliminados.getModel();
        
        int sRow = this.tabla_ueliminados.getSelectedRow();
        
        String codigo_aux = modelo.getValueAt(sRow, 0).toString();
        
        nombre = codigo_aux;
        System.out.println(nombre);
        int opcion = JOptionPane.showConfirmDialog(null, "¿Estas Seguro de Reactivar este Usuario?", "Reactivar Usuario", JOptionPane.YES_NO_OPTION);
        if(opcion == 0){
            reactivarUsuario();
            Prueba p = new Prueba("<html>"+"Usuario Activado <br> Correctamente"+"</html>");
            p.setVisible(true);
            imprimirEliminados();
        }
    }//GEN-LAST:event_tabla_ueliminadosMouseClicked

    private void limpiarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tabla_ueliminados.getModel();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_ueliminados;
    // End of variables declaration//GEN-END:variables
}
