/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_inventario;

import insumos.Pantalla_1;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import materia_prima_views.viewsmateriaPrima;
import Proveedores.proveedoresx;
import java.awt.Color;
import java.awt.Cursor;
import static sistema_inventario.Inicio.tipo_usuario;
import static sistema_inventario.Inicio.usuario_iniciado;

/**
 *
 * @author Usuario
 */
public class Menu_principal extends javax.swing.JFrame {

    /**
     * Creates new form menu_principal
     */
    public static Pantalla_1 pantalla1;
    public Menu_principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        //iconoFOrm();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes_insumos/sello_prolase.png")).getImage());
        nomb_regis.setText(usuario_iniciado);
        
        if(tipo_usuario.equals("Usuario")){
            this.jconfig.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_config1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel_alerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jconfig = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        nomb_regis = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel_config1.setBackground(new java.awt.Color(252, 249, 249));
        panel_config1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 18, 40, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 40, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PROLASEa.png"))); // NOI18N
        panel_config1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 50, 50));
        jLabel4.setText("Sistema de Gestion de Inventario ");
        panel_config1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 290, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cerrar Sesion");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 110, 30));

        panel_alerta.setBackground(new java.awt.Color(252, 249, 249));
        panel_alerta.setForeground(new java.awt.Color(240, 133, 150));
        panel_alerta.setEnabled(false);
        panel_alerta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/documentacion-1.png"))); // NOI18N
        jLabel1.setText("Documentacion Proveedores");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        panel_alerta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 230, 250));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/insumos.png"))); // NOI18N
        jLabel2.setText("Control de Insumos");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        panel_alerta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 190, 220));

        jconfig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        jconfig.setText("Configuraciones");
        jconfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jconfig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jconfig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jconfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jconfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jconfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jconfigMouseExited(evt);
            }
        });
        panel_alerta.add(jconfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 200, 230));
        panel_alerta.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 290, 10));
        panel_alerta.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 280, 20));

        nomb_regis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomb_regis.setToolTipText("");
        panel_alerta.add(nomb_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Bienvenido : ");
        panel_alerta.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/fondologo.png"))); // NOI18N
        panel_alerta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 890, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_config1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_alerta, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_config1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 540, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 81, Short.MAX_VALUE)
                    .addComponent(panel_alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void iconoFOrm() {
        URL url = getClass().getResource("/imagenes/PROLASEa.png");
        ImageIcon icono_inicio = new ImageIcon(url);
        setIconImage(icono_inicio.getImage());
    }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Salir del Programa", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jconfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jconfigMouseClicked
        Configuracion config = new Configuracion();
        config.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jconfigMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        pantalla1 = new Pantalla_1();
        pantalla1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        proveedoresx pro = new proveedoresx();
        pro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Inicio i = new Inicio();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        this.jLabel2.setOpaque(true);
        this.jLabel2.setCursor(new Cursor(HAND_CURSOR));
        this.jLabel2.setBackground(new Color(205, 223, 255));

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        this.jLabel2.setOpaque(false);
        this.jLabel2.setBackground(new Color(0, 0, 0));

    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        this.jLabel1.setOpaque(true);
        this.jLabel1.setCursor(new Cursor(HAND_CURSOR));
        this.jLabel1.setBackground(new Color(205, 223, 255));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        this.jLabel1.setOpaque(false);
        this.jLabel1.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jconfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jconfigMouseEntered
        // TODO add your handling code here:
        this.jconfig.setOpaque(true);
        this.jconfig.setCursor(new Cursor(HAND_CURSOR));
        this.jconfig.setBackground(new Color(205, 223, 255));
    }//GEN-LAST:event_jconfigMouseEntered

    private void jconfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jconfigMouseExited
        // TODO add your handling code here:
        this.jconfig.setOpaque(false);
        this.jconfig.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_jconfigMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jconfig;
    public static javax.swing.JLabel nomb_regis;
    public javax.swing.JPanel panel_alerta;
    private javax.swing.JPanel panel_config1;
    // End of variables declaration//GEN-END:variables
}
