/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_inventario;

import ConexionBDD.Conexion;
import ConexionBDD.Timer1;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class modificar_usuario extends javax.swing.JPanel {

    public static final String URL = "jdbc:mysql://127.0.0.1:3306/Sistemainventario";
    public static final String USERNAME = "root";
    public static final String PASSWORD = "cristian";

    public static PreparedStatement pat;

    private Timer1 t = new Timer1();
    

    public modificar_usuario() {
        initComponents();
        combo_tipo.addItem("Administrador");
        combo_tipo.addItem("Usuario");
        String txt_nombre = "";
        
        
    }

    
    
    public void eliminar() {
        t.iniciar1();
        Conexion cc = new Conexion();
        Connection con = cc.getConnection();
        boolean u = false;
        String nombre = this.jtextusuario1.getText().toString();
        
        try {
            con = cc.getConnection();
            
            
            pat = con.prepareStatement("UPDATE usuario SET estado_usuario = 0 "
                    + "WHERE nombre_usuario = ?");
            pat.setString(1, nombre);

            int res = pat.executeUpdate();
            
            t.pausar("Eliminar");
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Persona Eliminada");
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "No existe el Usuario que desea Eliminar");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tipo : " + e.getMessage());
        }

    }

    public void Actualizar() {
        t.iniciar1();
        Conexion cc = new Conexion();
        Connection con = cc.getConnection();
        String contraseña_usuario = String.valueOf(jtextcontra.getPassword());
        //Connection con=null;
        String nombre = this.jtextusuario1.getText().toString();
        boolean u = false;
        try {
            con = cc.getConnection();
            
            u = MainInicio.existeUsuario(nombre);
            
            if (u) {
                pat = con.prepareStatement("UPDATE usuario SET apellido_usuario=?,"
                        + "password_usuario=?,correo_usuario=?,tipo_usuario=? WHERE nombre_usuario=?");               
                pat.setString(1, jtextapellido.getText());
                pat.setString(2, contraseña_usuario);
                pat.setString(3, jtextcorreo.getText());
                pat.setString(4, combo_tipo.getSelectedItem().toString());
                pat.setString(5, jtextusuario1.getText());

                int res = pat.executeUpdate();
                
                t.pausar("Actualizar");
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Persona Modificada");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Modificar");
                }

            }else{
                JOptionPane.showMessageDialog(null, "<html>"+"No se puede actualizar el Nombre de Usuario <strong>[ "+ nombre +" ]</strong>, <br>"
                        + " debido a que es el identificador del registro "+"</html>", "Usuario No Registrado", JOptionPane.ERROR_MESSAGE);
            }
            
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error tipo : " + e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    public void consulta(String nombre) {
        t.iniciar1();
        Conexion cc = new Conexion();
        Connection con = cc.getConnection();
        
        try {
            con = cc.getConnection();           
            
            
            pat = con.prepareStatement("SELECT *FROM usuario WHERE nombre_usuario=?");
            pat.setString(1, nombre);
            ResultSet a = pat.executeQuery();

            if (a.next()) {
                jtextusuario.setText(a.getString("nombre_usuario"));
                jtextusuario1.setText(a.getString("nombre_usuario"));
                jtextapellido.setText(a.getString("apellido_usuario"));
                jtextcontra.setText(a.getString("password_usuario"));
                jtextcorreo.setText(a.getString("correo_usuario"));
                combo_tipo.setSelectedItem(a.getString("tipo_usuario"));
                
                t.pausar("Consulta");
            } else {
                JOptionPane.showMessageDialog(null, "No existe ese nombre, Ingrese el Nombre de algun Usuario");
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al buscar");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtextcorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtextapellido = new javax.swing.JTextField();
        jtextcontra = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jtextusuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        combo_tipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jtextusuario1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBackground(new java.awt.Color(252, 249, 249));
        jPanel2.setPreferredSize(new java.awt.Dimension(743, 560));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 17, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(5, 50, 50));
        jLabel9.setText("Nombre:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 195, 110, 30));

        jtextcorreo.setBackground(new java.awt.Color(102, 102, 102));
        jtextcorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtextcorreo.setForeground(new java.awt.Color(255, 255, 255));
        jtextcorreo.setText("Correo Electronico");
        jtextcorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 103, 95)));
        jtextcorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextcorreoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtextcorreoMousePressed(evt);
            }
        });
        jtextcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextcorreoActionPerformed(evt);
            }
        });
        jPanel2.add(jtextcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 356, 170, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(5, 50, 50));
        jLabel10.setText("Apellido:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 243, 110, 30));

        jtextapellido.setBackground(new java.awt.Color(102, 102, 102));
        jtextapellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtextapellido.setForeground(new java.awt.Color(255, 255, 255));
        jtextapellido.setText("  Ingrese Apellido");
        jtextapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 103, 95)));
        jtextapellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextapellidoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtextapellidoMousePressed(evt);
            }
        });
        jtextapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextapellidoActionPerformed(evt);
            }
        });
        jtextapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtextapellidoKeyTyped(evt);
            }
        });
        jPanel2.add(jtextapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 245, 170, 30));

        jtextcontra.setBackground(new java.awt.Color(102, 102, 102));
        jtextcontra.setForeground(new java.awt.Color(255, 255, 255));
        jtextcontra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 103, 95)));
        jtextcontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextcontraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtextcontraMousePressed(evt);
            }
        });
        jtextcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextcontraActionPerformed(evt);
            }
        });
        jPanel2.add(jtextcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 306, 170, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(5, 50, 50));
        jLabel12.setText("Correo Electronico: ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 354, 174, 30));

        jtextusuario.setBackground(new java.awt.Color(102, 102, 102));
        jtextusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtextusuario.setForeground(new java.awt.Color(255, 255, 255));
        jtextusuario.setText("   Ingrese Nombre ");
        jtextusuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 103, 95), 1, true));
        jtextusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextusuarioMouseClicked(evt);
            }
        });
        jtextusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextusuarioActionPerformed(evt);
            }
        });
        jtextusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtextusuarioKeyTyped(evt);
            }
        });
        jPanel2.add(jtextusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 74, 170, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(5, 50, 50));
        jLabel13.setText("Tipo de usuario");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 404, 160, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(5, 50, 50));
        jLabel14.setText("Contraseña:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 303, 173, 30));

        combo_tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combo_tipoMousePressed(evt);
            }
        });
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });
        jPanel2.add(combo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 404, 170, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/actualizar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/actualiz2.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/actualiz2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/actualiz2.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 140, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/buscar.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 36, 103, 84));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/eliminar.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/elimina2.png"))); // NOI18N
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/elimina2.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/elimina2.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 120, 60));

        jtextusuario1.setBackground(new java.awt.Color(102, 102, 102));
        jtextusuario1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtextusuario1.setForeground(new java.awt.Color(255, 255, 255));
        jtextusuario1.setText("  Ingrese Nombre");
        jtextusuario1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 103, 95), 1, true));
        jtextusuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtextusuario1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtextusuario1MousePressed(evt);
            }
        });
        jtextusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextusuario1ActionPerformed(evt);
            }
        });
        jtextusuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtextusuario1KeyTyped(evt);
            }
        });
        jPanel2.add(jtextusuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 195, 170, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/agrega1.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_login/fondologo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 10, 850, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtextcorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextcorreoMouseClicked
        if(jtextcorreo.getText().toString().trim().equals("Correo Electronico")){
            jtextcorreo.setText("");
        }
    }//GEN-LAST:event_jtextcorreoMouseClicked

    private void jtextcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextcorreoActionPerformed

    private void jtextapellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextapellidoMouseClicked
        if(jtextapellido.getText().toString().trim().equals("Ingrese Apellido")){
            jtextapellido.setText("");
        } 
    }//GEN-LAST:event_jtextapellidoMouseClicked

    private void jtextapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextapellidoActionPerformed

    private void jtextapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextapellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtextapellidoKeyTyped

    private void jtextcontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextcontraMouseClicked
        if(jtextcontra.getPassword().toString().trim().equals("*********")){
            jtextcontra.setText("");
        } 
    }//GEN-LAST:event_jtextcontraMouseClicked

    private void jtextcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextcontraActionPerformed

    private void jtextusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextusuarioMouseClicked
       
        if(this.jtextusuario.getText().toString().trim().equals("Ingrese Nombre")){
            this.jtextusuario.setText("");
        }
    }//GEN-LAST:event_jtextusuarioMouseClicked

    private void jtextusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextusuarioActionPerformed

    private void jtextusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextusuarioKeyTyped

        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtextusuarioKeyTyped

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed


    }//GEN-LAST:event_combo_tipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Seguro desea actulizar los Datos ?", "Exit", dialog);
        if (result == 0) {
            Actualizar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        consulta(jtextusuario.getText().toString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Seguro desea eliminarlo", "Exit", dialog);
        if (result == 0) {
            eliminar();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jtextusuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextusuario1MouseClicked
        // TODO add your handling code here:
       
        if (this.jtextusuario1.getText().toString().trim().equals("Ingrese Nombre")) {
            
            this.jtextusuario1.setText("");
        }
    }//GEN-LAST:event_jtextusuario1MouseClicked

    private void jtextusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextusuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextusuario1ActionPerformed

    private void jtextusuario1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextusuario1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextusuario1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String nombre = this.jtextusuario1.getText().trim();
        String apellido = this.jtextapellido.getText().trim();
        String password = new String(this.jtextcontra.getPassword());
        String email = this.jtextcorreo.getText().trim();
        String tipo = this.combo_tipo.getSelectedItem().toString();
        boolean validar = false;
        
        validar = MainInicio.existeUsuario(nombre);
        if (!validar) {
            if (!nombre.equals("") && !nombre.equals("Ingrese Nombre") && !apellido.equals("") && !apellido.equals("Ingrese Apellido")
                    && !password.equals("") && !email.equals("Correo Electronico")
                    && !email.equals("") && !tipo.equals("Seleccione")) {

                Usuario u = new Usuario();
                u.setNombre(nombre);
                u.setApellido(apellido);
                u.setPassword(password);
                u.setEmail(email);
                u.setTipo(tipo);
                u.setEstado(true);
                MainInicio.registrarUsuario(u);

                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
            }

        }else{
            JOptionPane.showMessageDialog(null, "<html>"+"Ya existe el Usuario <strong>[" + nombre + "]</strong> <br>"
                    + "Dos usuarios no pueden tener el mismo Nombre de Usuario"+"</html>");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void limpiarDatos(){
        this.jtextusuario1.setText("Ingrese Nombre");
        this.jtextapellido.setText("Ingrese Apellido");
        this.jtextcontra.setText("");
        this.jtextcorreo.setText("Correo Electronico");
        this.combo_tipo.setSelectedIndex(0);
        this.jtextusuario.setText("Ingrese Nombre");
    }
    
    private void jtextusuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextusuario1MousePressed
        
        
    }//GEN-LAST:event_jtextusuario1MousePressed

    private void jtextapellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextapellidoMousePressed
               
    }//GEN-LAST:event_jtextapellidoMousePressed

    private void jtextcontraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextcontraMousePressed
              
    }//GEN-LAST:event_jtextcontraMousePressed

    private void jtextcorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextcorreoMousePressed
        
        
    }//GEN-LAST:event_jtextcorreoMousePressed

    private void combo_tipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_tipoMousePressed

    }//GEN-LAST:event_combo_tipoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtextapellido;
    private javax.swing.JPasswordField jtextcontra;
    private javax.swing.JTextField jtextcorreo;
    private javax.swing.JTextField jtextusuario;
    private javax.swing.JTextField jtextusuario1;
    // End of variables declaration//GEN-END:variables
}
