/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proveedores;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sistema_inventario.Inicio;
import sistema_inventario.Menu_principal;

/**
 *
 * @author angel
 */
public class proveedoresx extends javax.swing.JFrame {

    /**
     * Creates new form proveedoresx
     */
    public proveedoresx() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes_insumos/sello_prolase.png")).getImage());
        getContentPane().setBackground(new Color(252,249,249));
        setBounds(0,0,1050,600);
        setLocationRelativeTo(null);
        Gestion_Proveedor g = new Gestion_Proveedor();
        proveedor_scroll.setViewportView(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_ver = new javax.swing.JLabel();
        panel_config1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        proveedor_scroll = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proveedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        btn_ver.setBackground(new java.awt.Color(252, 249, 249));
        btn_ver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ver.setText("Ver Documentos");
        btn_ver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ver.setOpaque(true);
        btn_ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_verMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_verMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_verMouseExited(evt);
            }
        });
        getContentPane().add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 160, 30));

        panel_config1.setBackground(new java.awt.Color(252, 249, 249));
        panel_config1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PROLASEa.png"))); // NOI18N
        panel_config1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(5, 50, 50));
        jLabel19.setText("Sistema de Gestion de Inventario -Proveedores");
        panel_config1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 400, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 40, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/minimizar.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        panel_config1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 50, 30));

        getContentPane().add(panel_config1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jButton4.setBackground(new java.awt.Color(252, 249, 249));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 60, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        proveedor_scroll.setViewportView(jPanel1);

        getContentPane().add(proveedor_scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1050, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Desea Salir del Programa","Exit",dialog);
        if(result== 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setState(Inicio.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Menu_principal Menu= new Menu_principal();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    private void btn_verMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verMouseClicked
        // TODO add your handling code here:
        Documentos d = new Documentos();
        proveedor_scroll.setViewportView(d);
        this.btn_ver.setBackground(new Color(29,45,80));
        this.btn_ver.setForeground(Color.white);
        
    }//GEN-LAST:event_btn_verMouseClicked

    private void btn_verMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_verMouseEntered

    private void btn_verMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_verMouseExited
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_verMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proveedoresx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proveedoresx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proveedoresx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proveedoresx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proveedoresx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_ver;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_config1;
    public static javax.swing.JScrollPane proveedor_scroll;
    // End of variables declaration//GEN-END:variables
}
