/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package materia_prima_views;


import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import materia_prima_model.MainMateria;

import materia_prima_model.MateriaPrima;




/**
 *
 * @author Stalyn
 */
public class viewInsertar extends javax.swing.JPanel {

  
    String fecha_aux = "";
    public viewInsertar() {
        initComponents();
        conseguirFecha();
        
        combo_tipo.addItem("Tipo A");
        combo_tipo.addItem("Tipo B");
        combo_tipo.addItem("Tipo C");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        txtViajes = new javax.swing.JTextField();
        txtRuta = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        CÓGIDO = new javax.swing.JLabel();
        CÓGIDO1 = new javax.swing.JLabel();
        CÓGIDO2 = new javax.swing.JLabel();
        CÓGIDO3 = new javax.swing.JLabel();
        CÓGIDO4 = new javax.swing.JLabel();
        CÓGIDO5 = new javax.swing.JLabel();
        CÓGIDO6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bntRegistrar1 = new javax.swing.JButton();
        bntRegistrar2 = new javax.swing.JButton();
        ma_fecha = new javax.swing.JTextField();
        combo_tipo = new javax.swing.JComboBox<String>();
        txtTotal = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        CÓGIDO.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO.setText("Código PLACA-VEHÍCULO");

        CÓGIDO1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO1.setText("Fecha de entrega");

        CÓGIDO2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO2.setText("Número de Viajes");

        CÓGIDO3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO3.setText("Ruta o Sector");

        CÓGIDO4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO4.setText("Cantidad");

        CÓGIDO5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO5.setText("Tipo");

        CÓGIDO6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        CÓGIDO6.setText("Total Registrado");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/controlw.png"))); // NOI18N

        bntRegistrar1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bntRegistrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materia_prima_views/nuevo1.png"))); // NOI18N
        bntRegistrar1.setText("Nuevo");
        bntRegistrar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrar1ActionPerformed(evt);
            }
        });

        bntRegistrar2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        bntRegistrar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materia_prima_views/cancelar2.png"))); // NOI18N
        bntRegistrar2.setText("Cancelar");
        bntRegistrar2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrar2ActionPerformed(evt);
            }
        });

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione el Tipo" }));

        guardar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/materia_prima_views/guardar1.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CÓGIDO)
                    .addComponent(CÓGIDO1)
                    .addComponent(CÓGIDO2)
                    .addComponent(CÓGIDO3)
                    .addComponent(CÓGIDO4)
                    .addComponent(CÓGIDO5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtViajes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuta)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ma_fecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_tipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bntRegistrar1)
                                .addGap(50, 50, 50)
                                .addComponent(guardar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(CÓGIDO6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(bntRegistrar2)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(CÓGIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CÓGIDO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ma_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtViajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CÓGIDO2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CÓGIDO3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CÓGIDO4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CÓGIDO5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CÓGIDO6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntRegistrar1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(guardar)
                        .addComponent(bntRegistrar2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void conseguirFecha(){
        java.util.Date fecha_defecto = new java.util.Date();
        System.out.println(fecha_defecto);
        //String formato_fecha = "hh:mm:ss a dd-MM-yyyy";
        String formato_fecha = "dd-MM-yyyy";
        SimpleDateFormat formato = new SimpleDateFormat(formato_fecha);
        System.out.println(formato.format(fecha_defecto));
        fecha_aux = formato.format(fecha_defecto);
        this.ma_fecha.setText(fecha_aux);
    }
    
    private void bntRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrar1ActionPerformed
            limpiar();
    }//GEN-LAST:event_bntRegistrar1ActionPerformed
    public void limpiar(){
    txtCantidad.setText(" ");
    txtCodigo.setText(" ");
    //txtFecha.setText(" ");
    txtRuta.setText(" ");
    txtTotal.setText(" ");
    txtViajes.setText(" ");
    combo_tipo.setSelectedItem("Seleccione el Tipo");
    
    }
    private void bntRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrar2ActionPerformed
            limpiar();
    }//GEN-LAST:event_bntRegistrar2ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
      
        if(!txtCantidad.getText().isEmpty() && !txtCodigo.getText().isEmpty()
           && !txtRuta.getText().isEmpty() && !txtViajes.getText().isEmpty() 
                && !combo_tipo.getSelectedItem().toString().equals("Seleccione el Tipo"))
        {
            
            MateriaPrima ma = new MateriaPrima();
            ma.setCodigo(txtCodigo.getText());
            
            //ma.setFecha(((JTextField)jdFecha.getDateEditor().getUiComponent()).getText());
            ma.setFecha(this.ma_fecha.getText());
            int viajes = 0;
            viajes = Integer.parseInt(txtViajes.getText());
            ma.setViajes(viajes);
            ma.setLocalidad(txtRuta.getText());
            float cantidad = 0;
            cantidad = Float.parseFloat(txtCantidad.getText());
            ma.setCantidad(cantidad);
            ma.setTipo(combo_tipo.getSelectedItem().toString());
            float totalM = 0;
            totalM = viajes*cantidad;
            //totalM = Float.parseFloat(txtTotal.getText());
            ma.setTotal(totalM);
            String cadena= Float.toString(totalM )+" Litros";
            txtTotal.setText(cadena);
            
            ma.setEstado("TRUE");
            MainMateria.crearMateria(ma);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS CAMPOS");
        }
        
            // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CÓGIDO;
    private javax.swing.JLabel CÓGIDO1;
    private javax.swing.JLabel CÓGIDO2;
    private javax.swing.JLabel CÓGIDO3;
    private javax.swing.JLabel CÓGIDO4;
    private javax.swing.JLabel CÓGIDO5;
    private javax.swing.JLabel CÓGIDO6;
    private javax.swing.JButton bntRegistrar1;
    private javax.swing.JButton bntRegistrar2;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField ma_fecha;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txtViajes;
    // End of variables declaration//GEN-END:variables
}
